# Investigating fpl data

In [1]:
import pandas as pd

In [2]:
pl_16_17 = pd.read_csv("../data/team_stats_2016_17.csv")
pl_16_17

     match_id           date team  goals    xg  goals_c  xg_c
0      855172  14th Aug 2016  BOU      1  0.00        3  0.00
1      855172  14th Aug 2016  MUN      3  0.00        1  0.00
2      855173  14th Aug 2016  ARS      3  0.00        4  0.00
3      855173  14th Aug 2016  LIV      4  0.00        3  0.00
4      855174  13th Aug 2016  BUR      0  0.00        1  0.00
..        ...            ...  ...    ...   ...      ...   ...
755    855549  21st May 2017  STK      1  0.00        0  0.00
756    855550  21st May 2017  SWA      2  0.00        1  0.00
757    855550  21st May 2017  WBA      1  0.00        2  0.00
758    855551  21st May 2017  MCI      5  3.03        0  0.90
759    855551  21st May 2017  WAT      0  0.90        5  3.03

[760 rows x 7 columns]

In [3]:
team_matches = pl_16_17.groupby("team").size().reset_index(name='matches')
team_matches

   team  matches
0   ARS       38
1   BOU       38
2   BUR       38
3   CHE       38
4   CRY       38
5   EVE       38
6   HUL       38
7   LEI       38
8   LIV       38
9   MCI       38
10  MID       38
11  MUN       38
12  SOU       38
13  STK       38
14  SUN       38
15  SWA       38
16  TOT       38
17  WAT       38
18  WBA       38
19  WHU       38

In [6]:
pl_17_18 = pd.read_csv("../data/team_stats_2017_18.csv")
pl_17_18

     match_id           date team  goals    xg  goals_c  xg_c
0      918893  11th Aug 2017  ARS      4  2.58        3  1.50
1      918893  11th Aug 2017  LEI      3  1.50        4  2.58
2      918894  12th Aug 2017  BHA      0  0.29        2  1.93
3      918894  12th Aug 2017  MCI      2  1.93        0  0.29
4      918895  12th Aug 2017  BUR      3  0.65        2  1.53
..        ...            ...  ...    ...   ...      ...   ...
755    919270  13th May 2018  SWA      1  3.00        2  1.64
756    919271  13th May 2018  LEI      4  1.39        5  1.76
757    919271  13th May 2018  TOT      5  1.76        4  1.39
758    919272  13th May 2018  EVE      1  1.69        3  1.13
759    919272  13th May 2018  WHU      3  1.13        1  1.69

[760 rows x 7 columns]

In [7]:
team_matches = pl_17_18.groupby("team").size().reset_index(name='matches')
team_matches

   team  matches
0   ARS       38
1   BHA       38
2   BOU       38
3   BUR       38
4   CHE       38
5   CRY       38
6   EVE       38
7   HUD       38
8   LEI       38
9   LIV       38
10  MCI       38
11  MUN       38
12  NEW       38
13  SOU       38
14  STK       38
15  SWA       38
16  TOT       38
17  WAT       38
18  WBA       38
19  WHU       38

In [10]:
pl_18_19 = pd.read_csv("../data/team_stats_2018_19.csv")
print(pl_18_19)
team_matches = pl_18_19.groupby("team").size().reset_index(name='matches')
team_matches

     match_id           date team  goals    xg  goals_c  xg_c
0      987592  11th Aug 2018  BOU      2  2.20        0  1.59
1      987592  11th Aug 2018  CAR      0  1.59        2  2.20
2      987593  12th Aug 2018  ARS      0  0.48        2  1.72
3      987593  12th Aug 2018  MCI      2  1.72        0  0.48
4      987594  11th Aug 2018  CRY      2  0.98        0  0.68
..        ...            ...  ...    ...   ...      ...   ...
755    987969  12th May 2019  SOU      1  0.62        1  0.73
756    987970  12th May 2019  EVE      2  2.02        2  0.63
757    987970  12th May 2019  TOT      2  0.63        2  2.02
758    987971  12th May 2019  WAT      1  2.23        4  3.07
759    987971  12th May 2019  WHU      4  3.07        1  2.23

[760 rows x 7 columns]

   team  matches
0   ARS       38
1   BHA       38
2   BOU       38
3   BUR       38
4   CAR       38
5   CHE       38
6   CRY       38
7   EVE       38
8   FUL       38
9   HUD       38
10  LEI       38
11  LIV       38
12  MCI       38
13  MUN       38
14  NEW       38
15  SOU       38
16  TOT       38
17  WAT       38
18  WHU       38
19  WOL       38

In [12]:
pl_19_20 = pd.read_csv("../data/team_stats_2019_20.csv")
print(pl_19_20)
team_matches = pl_19_20.groupby("team").size().reset_index(name='matches')
team_matches

     match_id           date team  goals    xg  goals_c  xg_c
0     1059702   9th Aug 2019  LIV      4  1.84        1  0.92
1     1059702   9th Aug 2019  NOR      1  0.92        4  1.84
2     1059703  10th Aug 2019  BOU      1  1.50        1  1.41
3     1059703  10th Aug 2019  SHU      1  1.41        1  1.50
4     1059704  10th Aug 2019  BUR      3  0.91        0  1.17
..        ...            ...  ...    ...   ...      ...   ...
755   1060079  26th Jul 2020  NEW      1  0.12        3  0.64
756   1060080  26th Jul 2020  SHU      1  1.44        3  1.67
757   1060080  26th Jul 2020  SOU      3  1.67        1  1.44
758   1060081  26th Jul 2020  AVL      1  1.00        1  0.85
759   1060081  26th Jul 2020  WHU      1  0.85        1  1.00

[760 rows x 7 columns]

   team  matches
0   ARS       38
1   AVL       38
2   BHA       38
3   BOU       38
4   BUR       38
5   CHE       38
6   CRY       38
7   EVE       38
8   LEI       38
9   LIV       38
10  MCI       38
11  MUN       38
12  NEW       38
13  NOR       38
14  SHU       38
15  SOU       38
16  TOT       38
17  WAT       38
18  WHU       38
19  WOL       38

In [13]:
pl_20_21 = pd.read_csv("../data/team_stats_2020_21.csv")
print(pl_20_21)
team_matches = pl_20_21.groupby("team").size().reset_index(name='matches')
team_matches

     match_id           date team  goals    xg  goals_c  xg_c
0     2128287  12th Sep 2020  CRY      1  1.11        0  0.90
1     2128287  12th Sep 2020  SOU      0  0.90        1  1.11
2     2128288  12th Sep 2020  ARS      3  1.97        0  0.15
3     2128288  12th Sep 2020  FUL      0  0.15        3  1.97
4     2128289  12th Sep 2020  LEE      3  0.32        4  2.76
..        ...            ...  ...    ...   ...      ...   ...
753   2128663  23rd May 2021  SHU      1  0.49        0  1.06
754   2128664  23rd May 2021  SOU      0  1.51        3  1.33
755   2128664  23rd May 2021  WHU      3  1.33        0  1.51
756   2128665  23rd May 2021  MUN      2  2.06        1  0.86
757   2128665  23rd May 2021  WOL      1  0.86        2  2.06

[758 rows x 7 columns]

   team  matches
0   ARS       38
1   AVL       38
2   BHA       38
3   BUR       37
4   CHE       38
5   CRY       38
6   EVE       38
7   FUL       38
8   LEE       38
9   LEI       38
10  LIV       38
11  MCI       38
12  MUN       37
13  NEW       38
14  SHU       38
15  SOU       38
16  TOT       38
17  WBA       38
18  WHU       38
19  WOL       38

# Suspect