# Finding Player Lookalikes

When a new player joins the league, as a work around to provide them historical data, we will find a player in a similar posiiton at the same club. They will use this player's data until they can build up some historical data of their own.

In [2]:
import pandas as pd

In [3]:
fantasy = pd.read_csv('../data/master/master_fantasy.csv')
fantasy

,match_id,nick_name,full_name,pos,team,cost,mins,goals,assists,cs,goals_c,own_goals,y_c,r_c,bonus,points
0,918893,Cech,Petr Cech,Goalkeeper,ARS,0.0,90,0,0,0,3,0,0,0,0,0
1,918893,Walcott,Theo Walcott,Midfielder,ARS,0.0,21,0,0,0,0,0,0,0,0,0
2,918893,Ozil,Mesut Ozil,Midfielder,ARS,0.0,90,0,0,0,3,0,0,0,0,0
3,918893,Monreal,Nacho Monreal,Defender,ARS,0.0,90,0,0,0,3,0,0,0,0,0
4,918893,Ramsey,Aaron Ramsey,Midfielder,ARS,0.0,29,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86711,2444849,Ait Nouri,Rayan Ait Nouri,Defender,WOL,6.0,65,0,0,0,1,0,0,0,0,2
86712,2444849,Rodrigo Gomes,Rodrigo Martins Gomes,Midfielder,WOL,4.5,30,0,0,0,0,0,0,0,0,1
86713,2444849,André,André Trindade da Costa Neto,Midfielder,WOL,5.5,90,0,0,0,1,0,0,0,0,2
86714,2444849,Toti,Toti António Gomes,Defender,WOL,4.5,90,0,0,0,1,0,0,0,0,2
86715,2444849,Agbadou,Emmanuel Agbadou,Defender,WOL,4.5,90,0,0,0,1,0,0,0,0,2

In [4]:
fantasy[(fantasy.cost == 0) & (fantasy.mins > 0)]

,match_id,nick_name,full_name,pos,team,cost,mins,goals,assists,cs,goals_c,own_goals,y_c,r_c,bonus,points
0,918893,Cech,Petr Cech,Goalkeeper,ARS,0.0,90,0,0,0,3,0,0,0,0,0
1,918893,Walcott,Theo Walcott,Midfielder,ARS,0.0,21,0,0,0,0,0,0,0,0,0
2,918893,Ozil,Mesut Ozil,Midfielder,ARS,0.0,90,0,0,0,3,0,0,0,0,0
3,918893,Monreal,Nacho Monreal,Defender,ARS,0.0,90,0,0,0,3,0,0,0,0,0
4,918893,Ramsey,Aaron Ramsey,Midfielder,ARS,0.0,29,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63737,2293189,Firmino,Roberto Firmino Barbosa de Oliveira,Forward,LIV,0.0,57,1,0,0,3,0,0,0,0,5
63749,2293189,Walcott,Theo Walcott,Midfielder,SOU,0.0,73,0,1,0,4,0,0,0,0,5
63752,2293189,Elyounoussi,Mohammed Elyounoussi,Midfielder,SOU,0.0,60,0,0,0,2,0,0,0,0,2
63758,2293189,Lyanco,Lyanco Evangelista Silveira Neves Vojnovic,Defender,SOU,0.0,90,0,1,0,4,0,0,0,0,3
63760,2293189,Ballard,Dominic Ballard,Forward,SOU,0.0,12,0,0,0,0,0,0,0,0,1

In [5]:
fantasy[fantasy.full_name == 'Mohamed Salah']

,match_id,nick_name,full_name,pos,team,cost,mins,goals,assists,cs,goals_c,own_goals,y_c,r_c,bonus,points
231,918901,Salah,Mohamed Salah,Midfielder,LIV,14.5,86,1,1,0,2,0,0,0,0,0
409,918907,Salah,Mohamed Salah,Midfielder,LIV,14.5,34,0,0,0,0,0,0,0,0,0
688,918917,Salah,Mohamed Salah,Midfielder,LIV,14.5,90,1,1,1,0,0,0,0,0,0
979,918928,Salah,Mohamed Salah,Midfielder,LIV,14.5,45,0,0,0,1,0,0,0,0,0
1239,918937,Salah,Mohamed Salah,Midfielder,LIV,14.5,90,1,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85304,2444804,Salah,Mohamed Salah,Midfielder,LIV,14.5,90,1,0,0,1,0,0,0,1,8
85628,2444814,Salah,Mohamed Salah,Midfielder,LIV,14.5,90,0,0,0,3,0,0,0,0,2
85901,2444823,Salah,Mohamed Salah,Midfielder,LIV,14.5,90,0,0,0,2,0,0,0,0,2
86207,2444833,Salah,Mohamed Salah,Midfielder,LIV,14.5,90,0,0,0,3,0,0,0,0,2
86520,2444843,Salah,Mohamed Salah,Midfielder,LIV,14.5,90,1,0,0,1,0,0,0,3,10

It seems any player that has left the premier league has their cost set to 0, which might help our workaround or might not. Also, the players current cost shows as their historic cost. eek.

This changes our workaround for historic data. As we cant compare historic player costs. hmmmm

In [6]:
player_data = fantasy[['match_id', 'nick_name', 'full_name', 'pos', 'team', 'cost']]

In [7]:
player_data['season'] = 'none'
player_data['first_appearance'] = 0

/tmp/ipykernel_337392/2932675947.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  player_data['season'] = 'none'
/tmp/ipykernel_337392/2932675947.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  player_data['first_appearance'] = 0

In [8]:
player_data.loc[(player_data['match_id'] >= 918893) & (player_data['match_id'] <= 919272), 'season'] = '17-18'
player_data.loc[(player_data['match_id'] >= 987592) & (player_data['match_id'] <= 987971), 'season'] = '18-19'
player_data.loc[(player_data['match_id'] >= 1059702) & (player_data['match_id'] <= 1060081), 'season'] = '19-20'
player_data.loc[(player_data['match_id'] >= 2128286) & (player_data['match_id'] <= 2128665), 'season'] = '20-21'
player_data.loc[(player_data['match_id'] >= 2210271) & (player_data['match_id'] <= 2210650), 'season'] = '21-22'
player_data.loc[(player_data['match_id'] >= 2292810) & (player_data['match_id'] <= 2293189), 'season'] = '22-23'
player_data.loc[(player_data['match_id'] >= 2367538) & (player_data['match_id'] <= 2367917), 'season'] = '23-24'
player_data.loc[(player_data['match_id'] >= 2444470) & (player_data['match_id'] <= 2444849), 'season'] = '24-25'

In [9]:
vaastav_17_18 = pd.read_csv('../data/Vastaav/players_raw_17_18.csv')
vaastav_18_19 = pd.read_csv('../data/Vastaav/players_raw_18_19.csv')
vaastav_19_20 = pd.read_csv('../data/Vastaav/players_raw_19_20.csv')
vaastav_20_21 = pd.read_csv('../data/Vastaav/players_raw_20_21.csv')
vaastav_21_22 = pd.read_csv('../data/Vastaav/players_raw_21_22.csv')
vaastav_22_23 = pd.read_csv('../data/Vastaav/players_raw_22_23.csv')
vaastav_23_24 = pd.read_csv('../data/Vastaav/players_raw_23_24.csv')
vaastav_24_25 = pd.read_csv('../data/Vastaav/players_raw_24_25.csv')

In [10]:
vaastav = [
    (vaastav_17_18, '17-18'),
    (vaastav_18_19, '18-19'),
    (vaastav_19_20, '19-20'),
    (vaastav_20_21, '20-21'),
    (vaastav_21_22, '21-22'),
    (vaastav_22_23, '22-23'),
    (vaastav_23_24, '23-24'),
    (vaastav_24_25, '24-25')
]

initial_costs = pd.DataFrame()

for table, season in vaastav:
    temp = table[['first_name', 'second_name', 'cost_change_start', 'now_cost']]
    temp['full_name'] = temp['first_name'] + ' ' + temp['second_name']
    temp['initial_cost'] = (temp['now_cost'] - temp['cost_change_start'])/10
    temp['season'] = season
    temp = temp[['full_name', 'initial_cost', 'season']]
    initial_costs = pd.concat([initial_costs, temp], ignore_index=True)

initial_costs

/tmp/ipykernel_337392/3267965119.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['full_name'] = temp['first_name'] + ' ' + temp['second_name']
/tmp/ipykernel_337392/3267965119.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['initial_cost'] = (temp['now_cost'] - temp['cost_change_start'])/10
/tmp/ipykernel_337392/3267965119.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['season'] = season
/tmp/ipykernel_337392/3267965119.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['full_name'] = temp['first_name'] + ' ' + temp['second_name']
/tmp/ipykernel_337392/3267965119.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['initial_cost'] = (temp['now_cost'] - temp['cost_change_start'])/10
/tmp/ipykernel_337392/3267965119.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['season'] = season
/tmp/ipykernel_337392/3267965119.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['full_name'] = temp['first_name'] + ' ' + temp['second_name']
/tmp/ipykernel_337392/3267965119.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['initial_cost'] = (temp['now_cost'] - temp['cost_change_start'])/10
/tmp/ipykernel_337392/3267965119.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['season'] = season
/tmp/ipykernel_337392/3267965119.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['full_name'] = temp['first_name'] + ' ' + temp['second_name']
/tmp/ipykernel_337392/3267965119.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['initial_cost'] = (temp['now_cost'] - temp['cost_change_start'])/10
/tmp/ipykernel_337392/3267965119.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['season'] = season
/tmp/ipykernel_337392/3267965119.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['full_name'] = temp['first_name'] + ' ' + temp['second_name']
/tmp/ipykernel_337392/3267965119.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['initial_cost'] = (temp['now_cost'] - temp['cost_change_start'])/10
/tmp/ipykernel_337392/3267965119.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['season'] = season
/tmp/ipykernel_337392/3267965119.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['full_name'] = temp['first_name'] + ' ' + temp['second_name']
/tmp/ipykernel_337392/3267965119.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['initial_cost'] = (temp['now_cost'] - temp['cost_change_start'])/10
/tmp/ipykernel_337392/3267965119.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['season'] = season
/tmp/ipykernel_337392/3267965119.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['full_name'] = temp['first_name'] + ' ' + temp['second_name']
/tmp/ipykernel_337392/3267965119.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['initial_cost'] = (temp['now_cost'] - temp['cost_change_start'])/10
/tmp/ipykernel_337392/3267965119.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['season'] = season
/tmp/ipykernel_337392/3267965119.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['full_name'] = temp['first_name'] + ' ' + temp['second_name']
/tmp/ipykernel_337392/3267965119.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['initial_cost'] = (temp['now_cost'] - temp['cost_change_start'])/10
/tmp/ipykernel_337392/3267965119.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['season'] = season

                                   full_name  initial_cost season
0                               David Ospina           5.0  17-18
1                                  Petr Cech           5.5  17-18
2                   Damian Emiliano Martinez           4.0  17-18
3                          Laurent Koscielny           6.0  17-18
4                            Per Mertesacker           5.0  17-18
...                                      ...           ...    ...
5829                        Emmanuel Agbadou           4.0  24-25
5830  Vítor Manuel de Oliveira Lopes Pereira           0.8  24-25
5831                            Nasser Djiga           4.5  24-25
5832                        Marshall Munetsi           5.0  24-25
5833                             Mateus Mané           4.5  24-25

[5834 rows x 3 columns]

In [11]:
initial_costs[initial_costs.initial_cost <4.0]

                                   full_name  initial_cost season
5062                            Mikel Arteta           1.5  24-25
5109                              Unai Emery           0.8  24-25
5151                           Andoni Iraola           1.1  24-25
5187                            Thomas Frank           0.8  24-25
5238                         Fabian Hürzeler           1.1  24-25
5286                            Enzo Maresca           1.5  24-25
5327                          Oliver Glasner           0.8  24-25
5360                             David Moyes           0.5  24-25
5394        Marco Alexandre Saraiva da Silva           1.1  24-25
5432                          Kieran McKenna           0.5  24-25
5472                    Ruud van Nistelrooij           0.5  24-25
5511                               Arne Slot           1.5  24-25
5547                           Pep Guardiola           1.5  24-25
5585       Ruben Filipe Marques Diogo Amorim           0.8  24-25
5627                              Eddie Howe           1.5  24-25
5663    Nuno Herlander Simões Espírito Santo           1.1  24-25
5704                              Simon Rusk           0.5  24-25
5751                        Ange Postecoglou           1.1  24-25
5787                           Graham Potter           0.5  24-25
5830  Vítor Manuel de Oliveira Lopes Pereira           0.8  24-25

In [12]:
initial_costs = initial_costs[initial_costs.initial_cost >= 4.0]

In [14]:
player_data_outer = pd.merge(player_data, initial_costs, on=['full_name', 'season'], how='outer', indicator=True)

# Rows that didn't merge
unmatched = player_data_outer[player_data_outer["_merge"] != "both"]

print(unmatched)

       match_id nick_name         full_name  pos team  cost season  \
0           NaN       NaN   Aaron Anselmino  NaN  NaN   NaN  24-25
46          NaN       NaN    Aaron Connolly  NaN  NaN   NaN  23-24
293         NaN       NaN      Aaron Hickey  NaN  NaN   NaN  24-25
479         NaN       NaN        Aaron Mooy  NaN  NaN   NaN  20-21
480         NaN       NaN    Aaron Ramsdale  NaN  NaN   NaN  17-18
...         ...       ...               ...  ...  ...   ...    ...
88903       NaN       NaN      Ørjan Nyland  NaN  NaN   NaN  19-20
88904       NaN       NaN      Ørjan Nyland  NaN  NaN   NaN  20-21
88905       NaN       NaN    Đorđe Petrović  NaN  NaN   NaN  23-24
88906       NaN       NaN    Đorđe Petrović  NaN  NaN   NaN  24-25
88907       NaN       NaN  Łukasz Fabiański  NaN  NaN   NaN  24-25

       first_appearance  initial_cost      _merge
0                   NaN           4.0  right_only
46                  NaN           4.5  right_only
293                 NaN           4.5  right_only
479                 NaN           5.0  right_only
480                 NaN           4.0  right_only
...                 ...           ...         ...
88903               NaN           4.5  right_only
88904               NaN           4.0  right_only
88905               NaN           4.5  right_only
88906               NaN           4.5  right_only
88907               NaN           4.0  right_only

[14662 rows x 10 columns]

In [15]:
unmatched

,match_id,nick_name,full_name,pos,team,cost,season,first_appearance,initial_cost,_merge
0,NaN,NaN,Aaron Anselmino,NaN,NaN,NaN,24-25,NaN,4.0,right_only
46,NaN,NaN,Aaron Connolly,NaN,NaN,NaN,23-24,NaN,4.5,right_only
293,NaN,NaN,Aaron Hickey,NaN,NaN,NaN,24-25,NaN,4.5,right_only
479,NaN,NaN,Aaron Mooy,NaN,NaN,NaN,20-21,NaN,5.0,right_only
480,NaN,NaN,Aaron Ramsdale,NaN,NaN,NaN,17-18,NaN,4.0,right_only
...,...,...,...,...,...,...,...,...,...,...
88903,NaN,NaN,Ørjan Nyland,NaN,NaN,NaN,19-20,NaN,4.5,right_only
88904,NaN,NaN,Ørjan Nyland,NaN,NaN,NaN,20-21,NaN,4.0,right_only
88905,NaN,NaN,Đorđe Petrović,NaN,NaN,NaN,23-24,NaN,4.5,right_only
88906,NaN,NaN,Đorđe Petrović,NaN,NaN,NaN,24-25,NaN,4.5,right_only
88907,NaN,NaN,Łukasz Fabiański,NaN,NaN,NaN,24-25,NaN,4.0,right_only

In [15]:
unmatched.drop_duplicates(subset=['full_name', 'season']).sort_values(by='match_id')

,match_id,nick_name,full_name,pos,team,cost,season,first_appearance,initial_cost,_merge
67970,918893.0,Ndidi,Onyinye Wilfred Ndidi,Midfielder,LEI,4.9,17-18,0.0,NaN,left_only
61002,918893.0,Ozil,Mesut Ozil,Midfielder,ARS,0.0,17-18,0.0,NaN,left_only
60122,918893.0,James (Matthew),Matthew James,Midfielder,LEI,0.0,17-18,0.0,NaN,left_only
78872,918894.0,Aguero,Sergio Aguero,Forward,MCI,0.0,17-18,0.0,NaN,left_only
28972,918895.0,Fabregas,Francesc Fábregas,Midfielder,CHE,0.0,17-18,0.0,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...
88903,NaN,NaN,Ørjan Nyland,NaN,NaN,NaN,19-20,NaN,4.5,right_only
88904,NaN,NaN,Ørjan Nyland,NaN,NaN,NaN,20-21,NaN,4.0,right_only
88905,NaN,NaN,Đorđe Petrović,NaN,NaN,NaN,23-24,NaN,4.5,right_only
88906,NaN,NaN,Đorđe Petrović,NaN,NaN,NaN,24-25,NaN,4.5,right_only
88907,NaN,NaN,Łukasz Fabiański,NaN,NaN,NaN,24-25,NaN,4.0,right_only

In [16]:
left = unmatched[unmatched['_merge'] == 'left_only'].drop_duplicates(subset=['full_name', 'season']).sort_values(by='match_id')
right = unmatched[unmatched['_merge'] == 'right_only'].drop_duplicates(subset=['full_name', 'season']).sort_values(by=['full_name', 'season'])

In [17]:
left

,match_id,nick_name,full_name,pos,team,cost,season,first_appearance,initial_cost,_merge
67970,918893.0,Ndidi,Onyinye Wilfred Ndidi,Midfielder,LEI,4.9,17-18,0.0,NaN,left_only
61002,918893.0,Ozil,Mesut Ozil,Midfielder,ARS,0.0,17-18,0.0,NaN,left_only
60122,918893.0,James (Matthew),Matthew James,Midfielder,LEI,0.0,17-18,0.0,NaN,left_only
78872,918894.0,Aguero,Sergio Aguero,Forward,MCI,0.0,17-18,0.0,NaN,left_only
28972,918895.0,Fabregas,Francesc Fábregas,Midfielder,CHE,0.0,17-18,0.0,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...
1222,2444696.0,Khusanov,Abduqodir Khusanov,Defender,MCI,5.5,24-25,0.0,NaN,left_only
10701,2444712.0,Chilwell,Benjamin Chilwell,Defender,CRY,4.6,24-25,0.0,NaN,left_only
87405,2444713.0,Willian,Willian Borges Da Silva,Midfielder,FUL,5.0,24-25,0.0,NaN,left_only
64298,2444720.0,Djiga,Nasser Yacouba Djiga,Defender,WOL,4.5,24-25,0.0,NaN,left_only
7956,2444729.0,Bella Kotchap,Armel Bella Kotchap,Defender,SOU,3.9,24-25,0.0,NaN,left_only

In [18]:
right

,match_id,nick_name,full_name,pos,team,cost,season,first_appearance,initial_cost,_merge
0,NaN,NaN,Aaron Anselmino,NaN,NaN,NaN,24-25,NaN,4.0,right_only
46,NaN,NaN,Aaron Connolly,NaN,NaN,NaN,23-24,NaN,4.5,right_only
293,NaN,NaN,Aaron Hickey,NaN,NaN,NaN,24-25,NaN,4.5,right_only
479,NaN,NaN,Aaron Mooy,NaN,NaN,NaN,20-21,NaN,5.0,right_only
480,NaN,NaN,Aaron Ramsdale,NaN,NaN,NaN,17-18,NaN,4.0,right_only
...,...,...,...,...,...,...,...,...,...,...
88903,NaN,NaN,Ørjan Nyland,NaN,NaN,NaN,19-20,NaN,4.5,right_only
88904,NaN,NaN,Ørjan Nyland,NaN,NaN,NaN,20-21,NaN,4.0,right_only
88905,NaN,NaN,Đorđe Petrović,NaN,NaN,NaN,23-24,NaN,4.5,right_only
88906,NaN,NaN,Đorđe Petrović,NaN,NaN,NaN,24-25,NaN,4.5,right_only
88907,NaN,NaN,Łukasz Fabiański,NaN,NaN,NaN,24-25,NaN,4.0,right_only

In [13]:
player_data = player_data.merge(initial_costs, on=['full_name', 'season'], how='left')
player_data

,match_id,nick_name,full_name,pos,team,cost,season,first_appearance,initial_cost
0,918893,Cech,Petr Cech,Goalkeeper,ARS,0.0,17-18,0,5.5
1,918893,Walcott,Theo Walcott,Midfielder,ARS,0.0,17-18,0,7.5
2,918893,Ozil,Mesut Ozil,Midfielder,ARS,0.0,17-18,0,NaN
3,918893,Monreal,Nacho Monreal,Defender,ARS,0.0,17-18,0,5.5
4,918893,Ramsey,Aaron Ramsey,Midfielder,ARS,0.0,17-18,0,7.0
...,...,...,...,...,...,...,...,...,...
86803,2444849,Ait Nouri,Rayan Ait Nouri,Defender,WOL,6.0,24-25,0,NaN
86804,2444849,Rodrigo Gomes,Rodrigo Martins Gomes,Midfielder,WOL,4.5,24-25,0,5.5
86805,2444849,André,André Trindade da Costa Neto,Midfielder,WOL,5.5,24-25,0,5.0
86806,2444849,Toti,Toti António Gomes,Defender,WOL,4.5,24-25,0,4.5
86807,2444849,Agbadou,Emmanuel Agbadou,Defender,WOL,4.5,24-25,0,4.0

In [20]:
player_data.head(50)

,match_id,nick_name,full_name,pos,team,cost,season,first_appearance,initial_cost
0,918893,Cech,Petr Cech,Goalkeeper,ARS,0.0,17-18,0,5.5
1,918893,Walcott,Theo Walcott,Midfielder,ARS,0.0,17-18,0,7.5
2,918893,Ozil,Mesut Ozil,Midfielder,ARS,0.0,17-18,0,NaN
3,918893,Monreal,Nacho Monreal,Defender,ARS,0.0,17-18,0,5.5
4,918893,Ramsey,Aaron Ramsey,Midfielder,ARS,0.0,17-18,0,7.0
5,918893,Giroud,Olivier Giroud,Forward,ARS,7.8,17-18,0,8.5
6,918893,Welbeck,Danny Welbeck,Forward,ARS,6.5,17-18,0,7.5
7,918893,Lacazette,Alexandre Lacazette,Forward,ARS,0.0,17-18,0,10.5
8,918893,Oxlade-Chamberlain,Alex Oxlade-Chamberlain,Midfielder,ARS,0.0,17-18,0,6.0
9,918893,Xhaka,Granit Xhaka,Midfielder,ARS,5.0,17-18,0,5.5
10,918893,Bellerín,Héctor Bellerín,Defender,ARS,0.0,17-18,0,6.0
11,918893,Kolasinac,Sead Kolasinac,Defender,ARS,0.0,17-18,0,6.0
12,918893,Elneny,Mohamed Elneny,Midfielder,ARS,4.4,17-18,0,4.5
13,918893,Holding,Rob Holding,Defender,ARS,4.0,17-18,0,5.0
14,918893,Morgan,Wes Morgan,Defender,LEI,0.0,17-18,0,4.5
15,918893,Schmeichel,Kasper Schmeichel,Goalkeeper,LEI,5.0,17-18,0,5.0
16,918893,Fuchs,Christian Fuchs,Defender,LEI,0.0,17-18,0,5.0
17,918893,Simpson (Danny),Danny Simpson,Defender,LEI,0.0,17-18,0,4.5
18,918893,Albrighton,Marc Albrighton,Midfielder,LEI,0.0,17-18,0,5.5
19,918893,James (Matthew),Matthew James,Midfielder,LEI,0.0,17-18,0,NaN
20,918893,Okazaki,Shinji Okazaki,Forward,LEI,0.0,17-18,0,5.5
21,918893,Maguire,Harry Maguire,Defender,LEI,4.5,17-18,0,5.0
22,918893,Vardy,Jamie Vardy,Forward,LEI,5.4,17-18,0,8.5
23,918893,Mahrez,Riyad Mahrez,Midfielder,LEI,7.5,17-18,0,8.5
24,918893,Amartey,Daniel Amartey,Midfielder,LEI,0.0,17-18,0,4.5
25,918893,Gray (Demarai),Demarai Gray,Midfielder,LEI,5.3,17-18,0,5.5
26,918893,Iheanacho,Kelechi Iheanacho,Forward,LEI,0.0,17-18,0,7.0
27,918893,Ndidi,Onyinye Wilfred Ndidi,Midfielder,LEI,4.9,17-18,0,NaN
28,918894,Murphy (Jamie),Jamie Murphy,Midfielder,BHA,0.0,17-18,0,5.0
29,918894,Bruno,Bruno Saltor Grau,Defender,BHA,0.0,17-18,0,4.5
30,918894,Murray,Glenn Murray,Forward,BHA,0.0,17-18,0,6.0
31,918894,Hemed,Tomer Hemed,Forward,BHA,0.0,17-18,0,5.0
32,918894,Stephens (Dale),Dale Stephens,Midfielder,BHA,0.0,17-18,0,4.5
33,918894,Suttner,Markus Suttner,Defender,BHA,0.0,17-18,0,4.5
34,918894,Groß,Pascal Groß,Midfielder,BHA,6.5,17-18,0,5.5
35,918894,Duffy,Shane Duffy,Defender,BHA,0.0,17-18,0,4.5
36,918894,Pröpper,Davy Pröpper,Midfielder,BHA,0.0,17-18,0,5.5
37,918894,Dunk,Lewis Dunk,Defender,BHA,4.5,17-18,0,4.5
38,918894,Knockaert,Anthony Knockaert,Midfielder,BHA,4.4,17-18,0,6.0
39,918894,March,Solomon March,Midfielder,BHA,6.0,17-18,0,5.0
40,918894,Brown (Isaiah),Isaiah Brown,Midfielder,BHA,0.0,17-18,0,5.5
41,918894,Mat Ryan,Mathew Ryan,Goalkeeper,BHA,0.0,17-18,0,4.5
42,918894,Kompany,Vincent Kompany,Defender,MCI,0.0,17-18,0,6.0
43,918894,Silva,David Silva,Midfielder,MCI,0.0,17-18,0,8.0
44,918894,Fernandinho,Fernando Luiz Rosa,Midfielder,MCI,0.0,17-18,0,5.0
45,918894,Aguero,Sergio Aguero,Forward,MCI,0.0,17-18,0,NaN
46,918894,Otamendi,Nicolás Otamendi,Defender,MCI,0.0,17-18,0,5.5
47,918894,Walker,Kyle Walker,Defender,MCI,4.5,17-18,0,6.5
48,918894,De Bruyne,Kevin De Bruyne,Midfielder,MCI,9.5,17-18,0,10.0
49,918894,Stones,John Stones,Defender,MCI,5.5,17-18,0,5.5

In [21]:
missing_costs = player_data[player_data.initial_cost.isna()].drop_duplicates(subset=['full_name', 'season'])
missing_costs

,match_id,nick_name,full_name,pos,team,cost,season,first_appearance,initial_cost
2,918893,Ozil,Mesut Ozil,Midfielder,ARS,0.0,17-18,0,NaN
19,918893,James (Matthew),Matthew James,Midfielder,LEI,0.0,17-18,0,NaN
27,918893,Ndidi,Onyinye Wilfred Ndidi,Midfielder,LEI,4.9,17-18,0,NaN
45,918894,Aguero,Sergio Aguero,Forward,MCI,0.0,17-18,0,NaN
68,918895,Brady,Robert Brady,Midfielder,BUR,0.0,17-18,0,NaN
...,...,...,...,...,...,...,...,...,...
82127,2444696,Khusanov,Abduqodir Khusanov,Defender,MCI,5.5,24-25,0,NaN
82583,2444712,Chilwell,Benjamin Chilwell,Defender,CRY,4.6,24-25,0,NaN
82609,2444713,Willian,Willian Borges Da Silva,Midfielder,FUL,5.0,24-25,0,NaN
82851,2444720,Djiga,Nasser Yacouba Djiga,Defender,WOL,4.5,24-25,0,NaN
83117,2444729,Bella Kotchap,Armel Bella Kotchap,Defender,SOU,3.9,24-25,0,NaN

In [22]:
missing_costs_list = []
left_list = []

for _, row in missing_costs.iterrows():
    missing_costs_list.append((row['full_name'], row['season']))

for _, row in left.iterrows():
    left_list.append((row['full_name'], row['season']))

count = 0

for name in missing_costs_list:
    if name not in left_list:
        print(name)
        count +=1 

print(count)

0

In [24]:
initial_costs['full_name'] = initial_costs['first_name'] + ' ' + initial_costs['second_name']
initial_costs['initial_cost'] = (initial_costs['now_cost'] - initial_costs['cost_change_start'])/10
initial_costs

/tmp/ipykernel_7938/3445844350.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  initial_costs['full_name'] = initial_costs['first_name'] + ' ' + initial_costs['second_name']
/tmp/ipykernel_7938/3445844350.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  initial_costs['initial_cost'] = (initial_costs['now_cost'] - initial_costs['cost_change_start'])/10

,first_name,second_name,cost_change_start,now_cost,full_name,initial_cost
0,David,Ospina,-2,48,David Ospina,5.0
1,Petr,Cech,-2,53,Petr Cech,5.5
2,Damian Emiliano,Martinez,0,40,Damian Emiliano Martinez,4.0
3,Laurent,Koscielny,0,60,Laurent Koscielny,6.0
4,Per,Mertesacker,-3,47,Per Mertesacker,5.0
...,...,...,...,...,...,...
642,Jordan,Hugill,-6,49,Jordan Hugill,5.5
643,Patrice,Evra,-4,41,Patrice Evra,4.5
644,Marcus,Browne,0,45,Marcus Browne,4.5
645,Josh,Pask,0,40,Josh Pask,4.0
646,Grady,Diangana,0,45,Grady Diangana,4.5

In [27]:
for index, row in missing_costs.iterrows():
    if row['full_name'] not in players1:
        print(row['full_name'], row['season'], row['team'], row['pos'])

Mesut Ozil 17-18 ARS Midfielder
Matthew James 17-18 LEI Midfielder
Onyinye Wilfred Ndidi 17-18 LEI Midfielder
Sergio Aguero 17-18 MCI Forward
Robert Brady 17-18 BUR Midfielder
Francesc Fábregas 17-18 CHE Midfielder
Patrick Van Aanholt 17-18 CRY Defender
Thomas Ince 17-18 HUD Midfielder
Rhu-Endly Martina 17-18 EVE Defender
Bojan Krkic 17-18 STK Midfielder
Luis Antonio Valencia 17-18 MUN Defender
Javier Hernández 17-18 WHU Forward
Ayoze Pérez Gutiérrez 17-18 NEW Forward
Moussa Dembélé 17-18 TOT Midfielder
Cedric Ricardo Alves Soares 17-18 SOU Defender
Oriol Romeu 17-18 SOU Midfielder
Thomas Carroll 17-18 SWA Midfielder
Roberto Firmino Barbosa de Oliveira 17-18 LIV Forward
Sadio Mane 17-18 LIV Midfielder
Jordan Ibe 17-18 BOU Midfielder
Matthew Phillips 17-18 WBA Midfielder
Ahmed El-Sayed Hegazy 17-18 WBA Defender
Ramadan Sobhy Ahmed 17-18 STK Midfielder
Chung-Yong Lee 17-18 CRY Midfielder
Ashley Roy Westwood 17-18 BUR Midfielder
José Heriberto Izquierdo 17-18 BHA Midfielder
Renato Júnior Luz Sanches 17-18 SWA Midfielder
Ilkay Gundogan 17-18 MCI Midfielder
Victor Nilsson-Lindelof 17-18 MUN Defender
Sung-Yueng Ki 17-18 SWA Midfielder
Phillip Bardsley 17-18 BUR Defender
Georges-Kévin Nkoudou Mbida 17-18 BUR Midfielder
Souleymane Bamba 18-19 CAR Defender
David Hoilett 18-19 CAR Midfielder
Daniel Ward 18-19 CAR Midfielder
Bobby DeCordova-Reid 18-19 CAR Forward
Mesut Ozil 18-19 ARS Midfielder
Sergio Aguero 18-19 MCI Forward
Ilkay Gundogan 18-19 MCI Midfielder
Patrick Van Aanholt 18-19 CRY Defender
Andre Schürrle 18-19 FUL Midfielder
Kouassi Ryan Sessegnon 18-19 FUL Midfielder
Kepa Arrizabalaga Revuelta 18-19 CHE Goalkeeper
Roberto Firmino Barbosa de Oliveira 18-19 LIV Forward
Sadio Mane 18-19 LIV Midfielder
Javier Hernández 18-19 WHU Forward
Onyinye Wilfred Ndidi 18-19 LEI Midfielder
David De Gea 18-19 MUN Goalkeeper
Victor Nilsson-Lindelof 18-19 MUN Defender
Ayoze Pérez Gutiérrez 18-19 NEW Forward
Moussa Dembélé 18-19 TOT Midfielder
Ashley Roy Westwood 18-19 BUR Midfielder
Cedric Ricardo Alves Soares 18-19 SOU Defender
Oriol Romeu 18-19 SOU Midfielder
Mohammed Elyounoussi 18-19 SOU Midfielder
João Moutinho 18-19 WOL Midfielder
Raul Alonso Jimenez Rodriguez 18-19 WOL Forward
Leonardo Bonatini Lohner Maia 18-19 WOL Forward
Helder Costa 18-19 WOL Midfielder
Diogo José Teixeira da Silva 18-19 WOL Midfielder
Ramadan Sobhy Ahmed 18-19 HUD Midfielder
Lucas Pérez Martínez 18-19 WHU Forward
Jordan Ibe 18-19 BOU Midfielder
Luis Antonio Valencia 18-19 MUN Defender
Sung-Yueng Ki 18-19 NEW Midfielder
Phillip Bardsley 18-19 BUR Defender
Ashley Richards 18-19 CAR Defender
Greg Cunningham 18-19 CAR Defender
Romain Saiss 18-19 WOL Midfielder
José Heriberto Izquierdo 18-19 BHA Midfielder
Robert Brady 18-19 BUR Midfielder
Francesc Fábregas 18-19 CHE Midfielder
Sergio Rico González 18-19 FUL Goalkeeper
Caglar Söyüncü 18-19 LEI Defender
Yann Valery 18-19 SOU Defender
Georges-Kévin Nkoudou Mbida 18-19 TOT Midfielder
Havard Nordtveit 18-19 FUL Defender
Roberto Firmino Barbosa de Oliveira 19-20 LIV Forward
Sadio Mane 19-20 LIV Midfielder
Kenneth McLean 19-20 NOR Midfielder
Ashley Roy Westwood 19-20 BUR Midfielder
Oriol Romeu 19-20 SOU Midfielder
Yann Valery 19-20 SOU Defender
Patrick Van Aanholt 19-20 CRY Defender
Ayoze Pérez Gutiérrez 19-20 LEI Midfielder
Onyinye Wilfred Ndidi 19-20 LEI Midfielder
Caglar Söyüncü 19-20 LEI Defender
João Moutinho 19-20 WOL Midfielder
Raul Alonso Jimenez Rodriguez 19-20 WOL Forward
Romain Saiss 19-20 WOL Defender
Diogo José Teixeira da Silva 19-20 WOL Midfielder
Ahmed Elmohamady 19-20 AVL Defender
José Ignacio Peleteiro Ramallo 19-20 AVL Midfielder
Björn Engels 19-20 AVL Defender
Mahmoud Hassan 19-20 AVL Midfielder
Wesley Moraes Ferreira da Silva 19-20 AVL Forward
Georges-Kévin Nkoudou Mbida 19-20 TOT Midfielder
Tanguy NDombele 19-20 TOT Midfielder
Sergio Aguero 19-20 MCI Forward
Ilkay Gundogan 19-20 MCI Midfielder
Rodrigo Hernández Cascante 19-20 MCI Midfielder
Javier Hernández 19-20 WHU Forward
Kepa Arrizabalaga Revuelta 19-20 CHE Goalkeeper
David De Gea 19-20 MUN Goalkeeper
Victor Nilsson-Lindelof 19-20 MUN Defender
Nicolas Pepe 19-20 ARS Midfielder
Sung-Yueng Ki 19-20 NEW Midfielder
Pedro Neto 19-20 WOL Midfielder
Jordan Ibe 19-20 BOU Midfielder
Frederic Guilbert 19-20 AVL Defender
Ismaila Sarr 19-20 WAT Midfielder
Cedric Ricardo Alves Soares 19-20 SOU Defender
Mesut Ozil 19-20 ARS Midfielder
Jesús Vallejo 19-20 WOL Defender
Robert Brady 19-20 BUR Midfielder
Jose Angel Esmoris Tasende 19-20 MCI Defender
Roberto Jiménez 19-20 WHU Goalkeeper
Ralf Fährmann 19-20 NOR Goalkeeper
Djibril Sidibe 19-20 EVE Defender
Muhamed Besic 19-20 SHU Midfielder
Kouassi Ryan Sessegnon 19-20 TOT Midfielder
Phillip Bardsley 19-20 BUR Defender
Örjan Nyland 19-20 AVL Goalkeeper
Emile Smith-Rowe 19-20 ARS Midfielder
Mbwana Aly Samatta 19-20 AVL Forward
Daniel Podence 19-20 WOL Midfielder
Matthew James 19-20 LEI Midfielder
Emiliano Martinez 19-20 ARS Goalkeeper
Ashley Roy Westwood 20-21 BUR Midfielder
Robert Brady 20-21 BUR Midfielder
David De Gea 20-21 MUN Goalkeeper
Oriol Romeu 20-21 SOU Midfielder
Mohamed Elneny 20-21 ARS Midfielder
Nicolas Pepe 20-21 ARS Midfielder
Gabriel dos Santos Magalhães 20-21 ARS Defender
Bobby DeCordova-Reid 20-21 FUL Forward
Aleksandar Mitrovic 20-21 FUL Forward
Ivan Cavaleiro 20-21 FUL Midfielder
Pablo Hernández 20-21 LEE Midfielder
Rodrigo Moreno Machado 20-21 LEE Forward
Helder Costa 20-21 LEE Midfielder
Roberto Firmino Barbosa de Oliveira 20-21 LIV Forward
Sadio Mane 20-21 LIV Midfielder
Emiliano Martinez 20-21 AVL Goalkeeper
Bertrand Traore 20-21 AVL Midfielder
Ilkay Gundogan 20-21 MCI Midfielder
Rodrigo Hernández Cascante 20-21 MCI Midfielder
Tanguy NDombele 20-21 TOT Midfielder
Ayoze Pérez Gutiérrez 20-21 LEI Midfielder
Onyinye Wilfred Ndidi 20-21 LEI Midfielder
Caglar Söyüncü 20-21 LEI Defender
Semi Ajayi 20-21 WBA Defender
Matheus Fellipe Costa Pereira 20-21 WBA Midfielder
Kepa Arrizabalaga Revuelta 20-21 CHE Goalkeeper
João Moutinho 20-21 WOL Midfielder
Raul Alonso Jimenez Rodriguez 20-21 WOL Forward
Romain Saiss 20-21 WOL Defender
Fernando Marçal de Oliveira 20-21 WOL Defender
Daniel Podence 20-21 WOL Midfielder
Pedro Neto 20-21 WOL Midfielder
Vitor Machado Ferreira 20-21 WOL Midfielder
Mahmoud Hassan 20-21 AVL Midfielder
Matthew Phillips 20-21 WBA Midfielder
Phillip Bardsley 20-21 BUR Defender
James Dunne 20-21 BUR Defender
Victor Nilsson-Lindelof 20-21 MUN Defender
Fabio Daniel Soares Silva 20-21 WOL Forward
Diogo José Teixeira da Silva 20-21 LIV Midfielder
Thiago Emiliano da Silva 20-21 CHE Defender
Nelson Semedo 20-21 WOL Defender
Ahmed Elmohamady 20-21 AVL Defender
Sergio Aguero 20-21 MCI Forward
Oluwatosin Adarabioyo 20-21 FUL Defender
Patrick Van Aanholt 20-21 CRY Defender
Said Benrahma 20-21 WHU Midfielder
Robert Sanchez 20-21 BHA Goalkeeper
Diego Javier Llorente Ríos 20-21 LEE Defender
Cedric Ricardo Alves Soares 20-21 ARS Defender
Emile Smith-Rowe 20-21 ARS Midfielder
Zackary Steffen 20-21 MCI Goalkeeper
Yann Valery 20-21 SOU Defender
Martin Odegaard 20-21 ARS Midfielder
Rúnar Rúnarsson 20-21 ARS Goalkeeper
João Manuel Neves Virgínia 20-21 EVE Goalkeeper
Wesley Moraes Ferreira da Silva 20-21 AVL Forward
José Heriberto Izquierdo 20-21 BHA Forward
Amad Diallo Traore 20-21 MUN Forward
Nicolas Pepe 21-22 ARS Midfielder
Emile Smith-Rowe 21-22 ARS Midfielder
Nuno Tavares 21-22 ARS Defender
Christian Norgaard 21-22 BRE Midfielder
Sergi Canos 21-22 BRE Defender
Robert Sanchez 21-22 BHA Goalkeeper
Ashley Roy Westwood 21-22 BUR Midfielder
Addji Keaninkin Marc-Israel Guehi 21-22 CRY Defender
Oriol Romeu 21-22 SOU Midfielder
Valentino Livramento 21-22 SOU Defender
Ayoze Pérez Gutiérrez 21-22 LEI Midfielder
Onyinye Wilfred Ndidi 21-22 LEI Midfielder
Caglar Söyüncü 21-22 LEI Defender
João Moutinho 21-22 WOL Midfielder
Raul Alonso Jimenez Rodriguez 21-22 WOL Forward
Romain Saiss 21-22 WOL Defender
Fernando Marçal de Oliveira 21-22 WOL Defender
José Pedro Malheiro de Sá 21-22 WOL Goalkeeper
Francisco António Machado Trincão 21-22 WOL Midfielder
Fabio Daniel Soares Silva 21-22 WOL Forward
Rodrigo Moreno Machado 21-22 LEE Midfielder
Helder Costa 21-22 LEE Midfielder
Junior Firpo 21-22 LEE Defender
David De Gea 21-22 MUN Goalkeeper
Victor Nilsson-Lindelof 21-22 MUN Defender
Said Benrahma 21-22 WHU Midfielder
Roberto Firmino Barbosa de Oliveira 21-22 LIV Forward
Sadio Mane 21-22 LIV Midfielder
Diogo José Teixeira da Silva 21-22 LIV Forward
Dimitrios Giannoulis 21-22 NOR Defender
Maximillian Aarons 21-22 NOR Defender
Ilkay Gundogan 21-22 MCI Midfielder
Emiliano Martinez 21-22 AVL Goalkeeper
Bertrand Traore 21-22 AVL Midfielder
Emiliano Buendía 21-22 AVL Midfielder
Peter Etebo 21-22 WAT Midfielder
Emmanuel Bonaventure Dennis 21-22 WAT Forward
Juan Camilo Hernández 21-22 WAT Forward
Cedric Ricardo Alves Soares 21-22 ARS Defender
Wesley Moraes Ferreira da Silva 21-22 AVL Forward
Imran Louza 21-22 WAT Midfielder
Rodrigo Hernández Cascante 21-22 MCI Midfielder
Kenneth McLean 21-22 NOR Midfielder
Nelson Semedo 21-22 WOL Defender
Diego Javier Llorente Ríos 21-22 LEE Defender
Mohamed Elneny 21-22 ARS Midfielder
Martin Odegaard 21-22 ARS Midfielder
Mohammed Elyounoussi 21-22 SOU Midfielder
Bryan Gil 21-22 TOT Midfielder
Raphael Varane 21-22 MUN Defender
Daniel Podence 21-22 WOL Midfielder
Gabriel dos Santos Magalhães 21-22 ARS Defender
Mads Roerslev 21-22 BRE Defender
Asmir Begovic 21-22 EVE Goalkeeper
Mathias Antonsen Normann 21-22 NOR Midfielder
Kepa Arrizabalaga Revuelta 21-22 CHE Goalkeeper
Tanguy NDombele 21-22 TOT Midfielder
Zackary Steffen 21-22 MCI Goalkeeper
Nicolas N'Koulou 21-22 WAT Defender
James Mcatee 21-22 MCI Midfielder
Kouassi Ryan Sessegnon 21-22 TOT Defender
Philippe Coutinho 21-22 AVL Midfielder
Vitaliy Mykolenko 21-22 EVE Defender
Pedro Neto 21-22 WOL Midfielder
Yann Valery 21-22 SOU Defender
Mahmoud Hassan 21-22 AVL Midfielder
Moises Caicedo 21-22 BHA Midfielder
Martin Odegaard 22-23 ARS Midfielder
Ben White 22-23 ARS Defender
Edward Nketiah 22-23 ARS Forward
Gabriel Teodoro Martinelli Silva 22-23 ARS Midfielder
Addji Keaninkin Marc-Israel Guehi 22-23 CRY Defender
Cheick Oumar Doucoure 22-23 CRY Midfielder
Philippe Coutinho 22-23 AVL Midfielder
Emiliano Martinez 22-23 AVL Goalkeeper
Emiliano Buendía 22-23 AVL Midfielder
Matthew Cash 22-23 AVL Defender
Jefferson Lerma 22-23 BOU Midfielder
Benjamin Chilwell 22-23 CHE Defender
Marc Cucurella 22-23 CHE Defender
Bamidele Alli 22-23 EVE Midfielder
Rúben Gonçalo Silva Nascimento Vinagre 22-23 EVE Defender
Vitaliy Mykolenko 22-23 EVE Defender
Bobby DeCordova-Reid 22-23 FUL Midfielder
Oluwatosin Adarabioyo 22-23 FUL Defender
Aleksandar Mitrovic 22-23 FUL Forward
João Maria Lobo Alves Palhinha Gonçalves 22-23 FUL Midfielder
Andreas Pereira 22-23 FUL Midfielder
Roberto Firmino Barbosa de Oliveira 22-23 LIV Forward
Fabio Carvalho 22-23 LIV Midfielder
Darwin Núñez 22-23 LIV Forward
Rodrigo Moreno Machado 22-23 LEE Midfielder
Diego Javier Llorente Ríos 22-23 LEE Defender
Marc Roca 22-23 LEE Midfielder
José Pedro Malheiro de Sá 22-23 WOL Goalkeeper
Rúben Diogo da Silva Neves 22-23 WOL Midfielder
Hee-Chan Hwang 22-23 WOL Midfielder
Daniel Podence 22-23 WOL Midfielder
Pedro Neto 22-23 WOL Midfielder
Rayan Ait Nouri 22-23 WOL Defender
Christian Norgaard 22-23 BRE Midfielder
Pelenda Joshua Dasilva 22-23 BRE Midfielder
Halil Dervisoglu 22-23 BRE Forward
Onyinye Wilfred Ndidi 22-23 LEI Midfielder
Miguel Almirón 22-23 NEW Midfielder
Joseph Willock 22-23 NEW Midfielder
Oriol Romeu 22-23 SOU Midfielder
Joe Aribo 22-23 SOU Midfielder
Yann Valery 22-23 SOU Defender
Romeo Lavia 22-23 SOU Midfielder
Ivan Perisic 22-23 TOT Defender
Heung-Min Son 22-23 TOT Midfielder
Kouassi Ryan Sessegnon 22-23 TOT Defender
Emerson Aparecido Leite de Souza Junior 22-23 TOT Defender
Solomon March 22-23 BHA Midfielder
Robert Sanchez 22-23 BHA Goalkeeper
Moises Caicedo 22-23 BHA Midfielder
David De Gea 22-23 MUN Goalkeeper
Bruno Miguel Borges Fernandes 22-23 MUN Midfielder
José Diogo Dalot Teixeira 22-23 MUN Defender
Alejandro Garnacho Ferreyra 22-23 MUN Midfielder
Ilkay Gundogan 22-23 MCI Midfielder
João Pedro Cavaco Cancelo 22-23 MCI Defender
Bernardo Mota Veiga de Carvalho e Silva 22-23 MCI Midfielder
Rúben Santos Gato Alves Dias 22-23 MCI Defender
Rodrigo Hernández Cascante 22-23 MCI Midfielder
Said Benrahma 22-23 WHU Midfielder
Pablo Fornals 22-23 WHU Midfielder
Emile Smith-Rowe 22-23 ARS Midfielder
Amadou Mvom Onana 22-23 EVE Midfielder
Mads Roerslev 22-23 BRE Defender
Raphael Varane 22-23 MUN Defender
Carlos Miguel Ribeiro Dias 22-23 NFO Midfielder
Luis Sinisterra 22-23 LEE Midfielder
Mohammed Elyounoussi 22-23 SOU Midfielder
Armel Bella Kotchap 22-23 SOU Defender
Adama Traoré 22-23 WOL Midfielder
Nelson Semedo 22-23 WOL Defender
Ayoze Pérez Gutiérrez 22-23 LEI Midfielder
Lyanco Evangelista Silveira Neves Vojnovic 22-23 SOU Defender
João Moutinho 22-23 WOL Midfielder
Raul Alonso Jimenez Rodriguez 22-23 WOL Forward
Jan-Paul van Hecke 22-23 BHA Defender
Emiliano Marcondes Camargo Hansen 22-23 BOU Midfielder
Emmanuel Bonaventure Dennis 22-23 NFO Forward
Carlos Henrique Jose Francisco Venancio 22-23 MUN Midfielder
Diogo José Teixeira da Silva 22-23 LIV Midfielder
Fábio Daniel Vieira 22-23 ARS Midfielder
Willian Borges Da Silva 22-23 FUL Midfielder
Carlos Vinicius Alves Morais 22-23 FUL Forward
Hamed Traore 22-23 BOU Midfielder
Kepa Arrizabalaga Revuelta 22-23 CHE Goalkeeper
Junior Firpo 22-23 LEE Defender
Bertrand Traore 22-23 AVL Midfielder
Ricardo Domingos Barbosa Pereira 22-23 LEI Defender
Hugo Bueno 22-23 WOL Defender
Ebere Paul Onuachu 22-23 SOU Forward
Javier Manquillo 22-23 NEW Defender
Marcus Vinícius Oliveira Alencar 22-23 ARS Midfielder
Jeremy Sarmiento 22-23 BHA Midfielder
Asmir Begovic 22-23 EVE Goalkeeper
Degnand Wilfried Gnonto 22-23 LEE Forward
Victor Nilsson-Lindelof 22-23 MUN Defender
Facundo Pellistri 22-23 MUN Midfielder
Sergi Canos 22-23 BRE Midfielder
Bryan Gil 22-23 TOT Midfielder
Cedric Ricardo Alves Soares 22-23 ARS Defender
Caglar Söyüncü 22-23 LEI Defender
Pape Sarr 22-23 TOT Midfielder
Matias Viña 22-23 BOU Defender
Arnaut Danjuma Groeneveld 22-23 TOT Midfielder
Valentino Livramento 22-23 SOU Defender
Benson Manuel 23-24 BUR Midfielder
Victor Alexander da Silva 23-24 BUR Defender
Ameen Al Dakhil 23-24 BUR Defender
Mateo Kovacic 23-24 MCI Midfielder
Bernardo Mota Veiga de Carvalho e Silva 23-24 MCI Midfielder
Rodrigo Hernández Cascante 23-24 MCI Midfielder
James Mcatee 23-24 MCI Midfielder
Maximillian Aarons 23-24 BOU Defender
Vladimir Coufal 23-24 WHU Defender
Said Benrahma 23-24 WHU Midfielder
Tomas Soucek 23-24 WHU Midfielder
Pablo Fornals 23-24 WHU Midfielder
Martin Odegaard 23-24 ARS Midfielder
Ben White 23-24 ARS Defender
Edward Nketiah 23-24 ARS Forward
Gabriel Teodoro Martinelli Silva 23-24 ARS Midfielder
Ola Aina 23-24 NFO Defender
Solomon March 23-24 BHA Midfielder
Jan-Paul van Hecke 23-24 BHA Defender
Amarii Bell 23-24 LUT Defender
Mads Andersen 23-24 LUT Defender
Ryan John Giles 23-24 LUT Defender
Issa Kabore 23-24 LUT Defender
Amadou Mvom Onana 23-24 EVE Midfielder
Willian Borges Da Silva 23-24 FUL Midfielder
Bobby DeCordova-Reid 23-24 FUL Midfielder
Raul Alonso Jimenez Rodriguez 23-24 FUL Forward
Aleksandar Mitrovic 23-24 FUL Forward
Andreas Pereira 23-24 FUL Midfielder
Sasa Lukic 23-24 FUL Midfielder
Philippe Coutinho 23-24 AVL Midfielder
Emiliano Martinez 23-24 AVL Goalkeeper
Matthew Cash 23-24 AVL Defender
Miguel Almirón 23-24 NEW Midfielder
Jefferson Lerma 23-24 CRY Midfielder
Addji Keaninkin Marc-Israel Guehi 23-24 CRY Defender
Cheick Oumar Doucoure 23-24 CRY Midfielder
Anel Ahmedhodzic 23-24 SHU Defender
Vinicius de Souza Costa 23-24 SHU Midfielder
Anis Ben Slimane 23-24 SHU Midfielder
Christian Norgaard 23-24 BRE Midfielder
Mads Roerslev 23-24 BRE Defender
Ivan Perisic 23-24 TOT Defender
Heung-Min Son 23-24 TOT Midfielder
Emerson Aparecido Leite de Souza Junior 23-24 TOT Defender
Pape Sarr 23-24 TOT Midfielder
Iyenoma Destiny Udogie 23-24 TOT Defender
Benjamin Chilwell 23-24 CHE Defender
Robert Sanchez 23-24 CHE Goalkeeper
Diogo José Teixeira da Silva 23-24 LIV Midfielder
Darwin Núñez 23-24 LIV Forward
Carlos Henrique Jose Francisco Venancio 23-24 MUN Midfielder
Raphael Varane 23-24 MUN Defender
Bruno Miguel Borges Fernandes 23-24 MUN Midfielder
Victor Nilsson-Lindelof 23-24 MUN Defender
Facundo Pellistri 23-24 MUN Midfielder
Alejandro Garnacho Ferreyra 23-24 MUN Midfielder
José Pedro Malheiro de Sá 23-24 WOL Goalkeeper
Hee-Chan Hwang 23-24 WOL Midfielder
Nelson Semedo 23-24 WOL Defender
Pedro Neto 23-24 WOL Midfielder
Rayan Ait Nouri 23-24 WOL Defender
Fabio Daniel Soares Silva 23-24 WOL Forward
Hugo Bueno 23-24 WOL Defender
Pelenda Joshua Dasilva 23-24 BRE Midfielder
João Maria Lobo Alves Palhinha Gonçalves 23-24 FUL Midfielder
Hamed Traore 23-24 BOU Midfielder
Joseph Gomez 23-24 LIV Defender
Rúben Santos Gato Alves Dias 23-24 MCI Defender
Valentino Livramento 23-24 NEW Defender
José Diogo Dalot Teixeira 23-24 MUN Defender
Moises Caicedo 23-24 CHE Midfielder
Edson Álvarez 23-24 WHU Midfielder
Fábio Daniel Vieira 23-24 ARS Midfielder
Oluwatosin Adarabioyo 23-24 FUL Defender
Bertrand Traore 23-24 AVL Midfielder
Johann Berg Gudmundsson 23-24 BUR Midfielder
Nuno Tavares 23-24 NFO Defender
Jéremy Doku 23-24 MCI Midfielder
Vitaliy Mykolenko 23-24 EVE Defender
Carlos Vinicius Alves Morais 23-24 FUL Forward
Anssumane Fati 23-24 BHA Midfielder
Emile Smith-Rowe 23-24 ARS Midfielder
Marc Cucurella 23-24 CHE Defender
Ehor Yarmolyuk 23-24 BRE Midfielder
Ionut Radu 23-24 BOU Goalkeeper
Bryan Gil 23-24 TOT Midfielder
Joseph Willock 23-24 NEW Midfielder
Odisseas Vlachodimos 23-24 NFO Goalkeeper
Fode Ballo-Toure 23-24 FUL Defender
Dorde Petrovic 23-24 CHE Goalkeeper
Enes Unal 23-24 BOU Forward
André Filipe Tavares Gomes 23-24 EVE Midfielder
Romeo Lavia 23-24 CHE Midfielder
Amad Diallo Traore 23-24 MUN Midfielder
Brandon Aguilera 23-24 NFO Midfielder
Cedric Ricardo Alves Soares 23-24 ARS Defender
Kaine Hayden 23-24 AVL Defender
Raul Alonso Jimenez Rodriguez 24-25 FUL Forward
Andreas Pereira 24-25 FUL Midfielder
Emile Smith-Rowe 24-25 FUL Midfielder
Sasa Lukic 24-25 FUL Midfielder
Carlos Henrique Jose Francisco Venancio 24-25 MUN Midfielder
Bruno Miguel Borges Fernandes 24-25 MUN Midfielder
José Diogo Dalot Teixeira 24-25 MUN Defender
Alejandro Garnacho Ferreyra 24-25 MUN Midfielder
Amad Diallo Traore 24-25 MUN Midfielder
Martin Odegaard 24-25 ARS Midfielder
Ben White 24-25 ARS Defender
Gabriel Teodoro Martinelli Silva 24-25 ARS Midfielder
José Pedro Malheiro de Sá 24-25 WOL Goalkeeper
Hee-Chan Hwang 24-25 WOL Midfielder
Daniel Podence 24-25 WOL Midfielder
Rayan Ait Nouri 24-25 WOL Defender
Jeremy Sarmiento 24-25 BHA Midfielder
Kaoru Mitoma 24-25 BHA Midfielder
Jan-Paul van Hecke 24-25 BHA Defender
Vitaliy Mykolenko 24-25 EVE Defender
Marcus Harness 24-25 IPS Midfielder
Sammie Szmodics 24-25 IPS Midfielder
Ali Ibrahim Karim Al Hamadi 24-25 IPS Forward
Omari Hutchinson 24-25 IPS Midfielder
Diogo José Teixeira da Silva 24-25 LIV Midfielder
Valentino Livramento 24-25 NEW Defender
Ben Brereton 24-25 SOU Midfielder
William Smallbone 24-25 SOU Midfielder
Yukinari Sugawara 24-25 SOU Defender
Carlos Alcaraz 24-25 SOU Midfielder
Julian Araujo 24-25 BOU Defender
Emiliano Martinez 24-25 AVL Goalkeeper
Matthew Cash 24-25 AVL Defender
Amadou Mvom Onana 24-25 AVL Midfielder
Jaden Philogene-Bidace 24-25 AVL Midfielder
Kosta Nedeljkovic 24-25 AVL Defender
Vladimir Coufal 24-25 WHU Defender
Tomas Soucek 24-25 WHU Midfielder
Christian Norgaard 24-25 BRE Midfielder
Mads Roerslev 24-25 BRE Defender
Fabio Carvalho 24-25 BRE Midfielder
Jefferson Lerma 24-25 CRY Midfielder
Addji Keaninkin Marc-Israel Guehi 24-25 CRY Defender
Ismaila Sarr 24-25 CRY Midfielder
Cheick Oumar Doucoure 24-25 CRY Midfielder
Marc Cucurella 24-25 CHE Defender
Robert Sanchez 24-25 CHE Goalkeeper
Pedro Neto 24-25 CHE Midfielder
Moises Caicedo 24-25 CHE Midfielder
Marc Guiu 24-25 CHE Forward
Romeo Lavia 24-25 CHE Midfielder
Renato da Palma Veiga 24-25 CHE Midfielder
Mateo Kovacic 24-25 MCI Midfielder

In [28]:
for index, row in player_data.iterrows():
    if row['full_name'] == 'Francesc Fàbregas Soler':
        print(row['full_name'], row['season'], row['team'], row['pos'], row['initial_cost'])

In [29]:
player_data[player_data.team == 'CHE'].drop_duplicates(subset=['full_name'])[['full_name', 'team']].sort_values(by='full_name').head(50)

                                full_name team
65769                          Alex Matos  CHE
69395                     Alfie Gilchrist  CHE
80                    Andreas Christensen  CHE
78                        Antonio Rüdiger  CHE
28682                       Armando Broja  CHE
64102                         Axel Disasi  CHE
32432                   Benjamin Chilwell  CHE
58250                   Benoît Badiashile  CHE
21818                       Billy Gilmour  CHE
6708                   Callum Hudson-Odoi  CHE
54358                  Carney Chukwuemeka  CHE
70373                      Cesare Casadei  CHE
82                         Charly Musonda  CHE
21156                   Christian Pulisic  CHE
69207                  Christopher Nkunku  CHE
64889                         Cole Palmer  CHE
52552                     Conor Gallagher  CHE
72                      César Azpilicueta  CHE
2507                    Daniel Drinkwater  CHE
58846                  David Datro Fofana  CHE
71             David Luiz Moreira Marinho  CHE
951                     Davide Zappacosta  CHE
66723  Deivid Washington de Souza Eugênio  CHE
54354                       Denis Zakaria  CHE
68444                      Dorde Petrovic  CHE
943                           Eden Hazard  CHE
32437                       Edouard Mendy  CHE
7839          Emerson Palmieri dos Santos  CHE
54660                      Enzo Fernández  CHE
4471                         Ethan Ampadu  CHE
28679                    Faustino Anjorin  CHE
21817                       Fikayo Tomori  CHE
79493                     Filip Jørgensen  CHE
69                      Francesc Fábregas  CHE
70                            Gary Cahill  CHE
16810                     Gonzalo Higuaín  CHE
32650                        Hakim Ziyech  CHE
64105                         Ian Maatsen  CHE
76180                        Jadon Sancho  CHE
81                           Jeremie Boga  CHE
71455                     Jimi Tauriainen  CHE
10538             Jorge Luiz Frello Filho  CHE
71458                     Josh Acheampong  CHE
54357                 João Félix Sequeira  CHE
31790                         Kai Havertz  CHE
52541                   Kalidou Koulibaly  CHE
10542          Kepa Arrizabalaga Revuelta  CHE
75493               Kiernan Dewsbury-Hall  CHE
21150                          Kurt Zouma  CHE
64111                    Lesley Ugochukwu  CHE

In [30]:
no_match = initial_costs.copy()
for index, row in player_data.iterrows():
    if pd.notna(row['initial_cost']):
        no_
    else:
        players2.append(row['full_name'])

NameError: name 'no_' is not defined

In [31]:
no_match = missing_costs[missing_costs.full_name.isin()]

TypeError: Series.isin() missing 1 required positional argument: 'values'

In [32]:
from difflib import SequenceMatcher
import pandas as pd

def similarity(a, b):
    return SequenceMatcher(None, a.lower(), b.lower()).ratio() * 100

matches = []
count = 0

for name1, season1 in left[["full_name", "season"]].itertuples(index=False):
    count += 1
    print(f"\n[{count}] Matching for: {name1} ({season1})")
    best_score = -1
    best_match = None

    for name2, season2 in right[["full_name", "season"]].itertuples(index=False):
        if season1 != season2:
            continue
        score = similarity(name1, name2)
        if score > best_score:
            best_score = score
            best_match = name2

    if best_match:
        # Prompt user
        response = input(f"Do these match? '{name1}' ~ '{best_match}' (Score: {best_score:.2f}) [y/n]: ").strip().lower()
        indicator = 1 if response == 'y' else 0

        matches.append({
            "name1": name1,
            "name2": best_match,
            "season": season1,
            "score": best_score,
            "match_indicator": indicator
        })

matches_df = pd.DataFrame(matches)
print(matches_df)

[1] Matching for: Onyinye Wilfred Ndidi (17-18)

[2] Matching for: Mesut Ozil (17-18)

[3] Matching for: Matthew James (17-18)

[4] Matching for: Sergio Aguero (17-18)

[5] Matching for: Francesc Fábregas (17-18)

[6] Matching for: Robert Brady (17-18)

[7] Matching for: Patrick Van Aanholt (17-18)

[8] Matching for: Thomas Ince (17-18)

[9] Matching for: Bojan Krkic (17-18)

[10] Matching for: Rhu-Endly Martina (17-18)

[11] Matching for: Luis Antonio Valencia (17-18)

[12] Matching for: Javier Hernández (17-18)

[13] Matching for: Ayoze Pérez Gutiérrez (17-18)

[14] Matching for: Moussa Dembélé (17-18)

[15] Matching for: Oriol Romeu (17-18)

[16] Matching for: Cedric Ricardo Alves Soares (17-18)

[17] Matching for: Thomas Carroll (17-18)

[18] Matching for: Roberto Firmino Barbosa de Oliveira (17-18)

[19] Matching for: Sadio Mane (17-18)

[20] Matching for: Jordan Ibe (17-18)

[21] Matching for: Ahmed El-Sayed Hegazy (17-18)

[22] Matching for: Matthew Phillips (17-18)

[23] Matching for: Ramadan Sobhy Ahmed (17-18)

[24] Matching for: Chung-Yong Lee (17-18)

[25] Matching for: Ashley Roy Westwood (17-18)

[26] Matching for: José Heriberto Izquierdo (17-18)

[27] Matching for: Renato Júnior Luz Sanches (17-18)

[28] Matching for: Ilkay Gundogan (17-18)

[29] Matching for: Victor Nilsson-Lindelof (17-18)

[30] Matching for: Sung-Yueng Ki (17-18)

[31] Matching for: Phillip Bardsley (17-18)

[32] Matching for: Georges-Kévin Nkoudou Mbida (17-18)

[33] Matching for: Daniel Ward (18-19)

[34] Matching for: David Hoilett (18-19)

[35] Matching for: Bobby DeCordova-Reid (18-19)

[36] Matching for: Souleymane Bamba (18-19)

[37] Matching for: Sergio Aguero (18-19)

[38] Matching for: Ilkay Gundogan (18-19)

[39] Matching for: Mesut Ozil (18-19)

[40] Matching for: Patrick Van Aanholt (18-19)

[41] Matching for: Andre Schürrle (18-19)

[42] Matching for: Kouassi Ryan Sessegnon (18-19)

[43] Matching for: Kepa Arrizabalaga Revuelta (18-19)

[44] Matching for: Javier Hernández (18-19)

[45] Matching for: Roberto Firmino Barbosa de Oliveira (18-19)

[46] Matching for: Sadio Mane (18-19)

[47] Matching for: Onyinye Wilfred Ndidi (18-19)

[48] Matching for: Victor Nilsson-Lindelof (18-19)

[49] Matching for: David De Gea (18-19)

[50] Matching for: Moussa Dembélé (18-19)

[51] Matching for: Ayoze Pérez Gutiérrez (18-19)

[52] Matching for: Cedric Ricardo Alves Soares (18-19)

[53] Matching for: Ashley Roy Westwood (18-19)

[54] Matching for: Oriol Romeu (18-19)

[55] Matching for: Mohammed Elyounoussi (18-19)

[56] Matching for: João Moutinho (18-19)

[57] Matching for: Helder Costa (18-19)

[58] Matching for: Diogo José Teixeira da Silva (18-19)

[59] Matching for: Raul Alonso Jimenez Rodriguez (18-19)

[60] Matching for: Leonardo Bonatini Lohner Maia (18-19)

[61] Matching for: Ramadan Sobhy Ahmed (18-19)

[62] Matching for: Lucas Pérez Martínez (18-19)

[63] Matching for: Jordan Ibe (18-19)

[64] Matching for: Luis Antonio Valencia (18-19)

[65] Matching for: Sung-Yueng Ki (18-19)

[66] Matching for: Phillip Bardsley (18-19)

[67] Matching for: Ashley Richards (18-19)

[68] Matching for: Greg Cunningham (18-19)

[69] Matching for: Romain Saiss (18-19)

[70] Matching for: José Heriberto Izquierdo (18-19)

[71] Matching for: Francesc Fábregas (18-19)

[72] Matching for: Robert Brady (18-19)

[73] Matching for: Sergio Rico González (18-19)

[74] Matching for: Caglar Söyüncü (18-19)

[75] Matching for: Yann Valery (18-19)

[76] Matching for: Georges-Kévin Nkoudou Mbida (18-19)

[77] Matching for: Havard Nordtveit (18-19)

[78] Matching for: Roberto Firmino Barbosa de Oliveira (19-20)

[79] Matching for: Kenneth McLean (19-20)

[80] Matching for: Sadio Mane (19-20)

[81] Matching for: Ashley Roy Westwood (19-20)

[82] Matching for: Yann Valery (19-20)

[83] Matching for: Oriol Romeu (19-20)

[84] Matching for: Patrick Van Aanholt (19-20)

[85] Matching for: João Moutinho (19-20)

[86] Matching for: Ayoze Pérez Gutiérrez (19-20)

[87] Matching for: Raul Alonso Jimenez Rodriguez (19-20)

[88] Matching for: Onyinye Wilfred Ndidi (19-20)

[89] Matching for: Diogo José Teixeira da Silva (19-20)

[90] Matching for: Romain Saiss (19-20)

[91] Matching for: Caglar Söyüncü (19-20)

[92] Matching for: José Ignacio Peleteiro Ramallo (19-20)

[93] Matching for: Wesley Moraes Ferreira da Silva (19-20)

[94] Matching for: Ahmed Elmohamady (19-20)

[95] Matching for: Mahmoud Hassan (19-20)

[96] Matching for: Tanguy NDombele (19-20)

[97] Matching for: Georges-Kévin Nkoudou Mbida (19-20)

[98] Matching for: Björn Engels (19-20)

[99] Matching for: Rodrigo Hernández Cascante (19-20)

[100] Matching for: Javier Hernández (19-20)

[101] Matching for: Sergio Aguero (19-20)

[102] Matching for: Ilkay Gundogan (19-20)

[103] Matching for: David De Gea (19-20)

[104] Matching for: Victor Nilsson-Lindelof (19-20)

[105] Matching for: Kepa Arrizabalaga Revuelta (19-20)

[106] Matching for: Nicolas Pepe (19-20)

[107] Matching for: Sung-Yueng Ki (19-20)

[108] Matching for: Pedro Neto (19-20)

[109] Matching for: Jordan Ibe (19-20)

[110] Matching for: Frederic Guilbert (19-20)

[111] Matching for: Ismaila Sarr (19-20)

[112] Matching for: Cedric Ricardo Alves Soares (19-20)

[113] Matching for: Mesut Ozil (19-20)

[114] Matching for: Jesús Vallejo (19-20)

[115] Matching for: Robert Brady (19-20)

[116] Matching for: Jose Angel Esmoris Tasende (19-20)

[117] Matching for: Roberto Jiménez (19-20)

[118] Matching for: Ralf Fährmann (19-20)

[119] Matching for: Djibril Sidibe (19-20)

[120] Matching for: Muhamed Besic (19-20)

[121] Matching for: Kouassi Ryan Sessegnon (19-20)

[122] Matching for: Phillip Bardsley (19-20)

[123] Matching for: Örjan Nyland (19-20)

[124] Matching for: Emile Smith-Rowe (19-20)

[125] Matching for: Mbwana Aly Samatta (19-20)

[126] Matching for: Daniel Podence (19-20)

[127] Matching for: Matthew James (19-20)

[128] Matching for: Emiliano Martinez (19-20)

[129] Matching for: Robert Brady (20-21)

[130] Matching for: Ashley Roy Westwood (20-21)

[131] Matching for: David De Gea (20-21)

[132] Matching for: Oriol Romeu (20-21)

[133] Matching for: Gabriel dos Santos Magalhães (20-21)

[134] Matching for: Nicolas Pepe (20-21)

[135] Matching for: Mohamed Elneny (20-21)

[136] Matching for: Ivan Cavaleiro (20-21)

[137] Matching for: Aleksandar Mitrovic (20-21)

[138] Matching for: Bobby DeCordova-Reid (20-21)

[139] Matching for: Pablo Hernández (20-21)

[140] Matching for: Roberto Firmino Barbosa de Oliveira (20-21)

[141] Matching for: Rodrigo Moreno Machado (20-21)

[142] Matching for: Sadio Mane (20-21)

[143] Matching for: Helder Costa (20-21)

[144] Matching for: Ilkay Gundogan (20-21)

[145] Matching for: Rodrigo Hernández Cascante (20-21)

[146] Matching for: Bertrand Traore (20-21)

[147] Matching for: Emiliano Martinez (20-21)

[148] Matching for: Tanguy NDombele (20-21)

[149] Matching for: Onyinye Wilfred Ndidi (20-21)

[150] Matching for: Semi Ajayi (20-21)

[151] Matching for: Caglar Söyüncü (20-21)

[152] Matching for: Ayoze Pérez Gutiérrez (20-21)

[153] Matching for: Matheus Fellipe Costa Pereira (20-21)

[154] Matching for: Kepa Arrizabalaga Revuelta (20-21)

[155] Matching for: Daniel Podence (20-21)

[156] Matching for: Pedro Neto (20-21)

[157] Matching for: João Moutinho (20-21)

[158] Matching for: Fernando Marçal de Oliveira (20-21)

[159] Matching for: Vitor Machado Ferreira (20-21)

[160] Matching for: Romain Saiss (20-21)

[161] Matching for: Raul Alonso Jimenez Rodriguez (20-21)

[162] Matching for: Mahmoud Hassan (20-21)

[163] Matching for: Matthew Phillips (20-21)

[164] Matching for: James Dunne (20-21)

[165] Matching for: Phillip Bardsley (20-21)

[166] Matching for: Victor Nilsson-Lindelof (20-21)

[167] Matching for: Fabio Daniel Soares Silva (20-21)

[168] Matching for: Diogo José Teixeira da Silva (20-21)

[169] Matching for: Thiago Emiliano da Silva (20-21)

[170] Matching for: Nelson Semedo (20-21)

[171] Matching for: Ahmed Elmohamady (20-21)

[172] Matching for: Sergio Aguero (20-21)

[173] Matching for: Oluwatosin Adarabioyo (20-21)

[174] Matching for: Patrick Van Aanholt (20-21)

[175] Matching for: Said Benrahma (20-21)

[176] Matching for: Robert Sanchez (20-21)

[177] Matching for: Diego Javier Llorente Ríos (20-21)

[178] Matching for: Cedric Ricardo Alves Soares (20-21)

[179] Matching for: Emile Smith-Rowe (20-21)

[180] Matching for: Zackary Steffen (20-21)

[181] Matching for: Yann Valery (20-21)

[182] Matching for: Martin Odegaard (20-21)

[183] Matching for: Rúnar Rúnarsson (20-21)

[184] Matching for: João Manuel Neves Virgínia (20-21)

[185] Matching for: Wesley Moraes Ferreira da Silva (20-21)

[186] Matching for: José Heriberto Izquierdo (20-21)

[187] Matching for: Amad Diallo Traore (20-21)

[188] Matching for: Emile Smith-Rowe (21-22)

[189] Matching for: Nicolas Pepe (21-22)

[190] Matching for: Nuno Tavares (21-22)

[191] Matching for: Sergi Canos (21-22)

[192] Matching for: Christian Norgaard (21-22)

[193] Matching for: Robert Sanchez (21-22)

[194] Matching for: Ashley Roy Westwood (21-22)

[195] Matching for: Addji Keaninkin Marc-Israel Guehi (21-22)

[196] Matching for: Valentino Livramento (21-22)

[197] Matching for: Oriol Romeu (21-22)

[198] Matching for: José Pedro Malheiro de Sá (21-22)

[199] Matching for: João Moutinho (21-22)

[200] Matching for: Francisco António Machado Trincão (21-22)

[201] Matching for: Onyinye Wilfred Ndidi (21-22)

[202] Matching for: Ayoze Pérez Gutiérrez (21-22)

[203] Matching for: Raul Alonso Jimenez Rodriguez (21-22)

[204] Matching for: Romain Saiss (21-22)

[205] Matching for: Fabio Daniel Soares Silva (21-22)

[206] Matching for: Fernando Marçal de Oliveira (21-22)

[207] Matching for: Caglar Söyüncü (21-22)

[208] Matching for: Helder Costa (21-22)

[209] Matching for: Victor Nilsson-Lindelof (21-22)

[210] Matching for: David De Gea (21-22)

[211] Matching for: Rodrigo Moreno Machado (21-22)

[212] Matching for: Junior Firpo (21-22)

[213] Matching for: Said Benrahma (21-22)

[214] Matching for: Roberto Firmino Barbosa de Oliveira (21-22)

[215] Matching for: Dimitrios Giannoulis (21-22)

[216] Matching for: Diogo José Teixeira da Silva (21-22)

[217] Matching for: Sadio Mane (21-22)

[218] Matching for: Maximillian Aarons (21-22)

[219] Matching for: Ilkay Gundogan (21-22)

[220] Matching for: Bertrand Traore (21-22)

[221] Matching for: Juan Camilo Hernández (21-22)

[222] Matching for: Emiliano Martinez (21-22)

[223] Matching for: Peter Etebo (21-22)

[224] Matching for: Emiliano Buendía (21-22)

[225] Matching for: Emmanuel Bonaventure Dennis (21-22)

[226] Matching for: Cedric Ricardo Alves Soares (21-22)

[227] Matching for: Wesley Moraes Ferreira da Silva (21-22)

[228] Matching for: Imran Louza (21-22)

[229] Matching for: Kenneth McLean (21-22)

[230] Matching for: Rodrigo Hernández Cascante (21-22)

[231] Matching for: Nelson Semedo (21-22)

[232] Matching for: Diego Javier Llorente Ríos (21-22)

[233] Matching for: Martin Odegaard (21-22)

[234] Matching for: Mohamed Elneny (21-22)

[235] Matching for: Mohammed Elyounoussi (21-22)

[236] Matching for: Bryan Gil (21-22)

[237] Matching for: Raphael Varane (21-22)

[238] Matching for: Daniel Podence (21-22)

[239] Matching for: Gabriel dos Santos Magalhães (21-22)

[240] Matching for: Mads Roerslev (21-22)

[241] Matching for: Asmir Begovic (21-22)

[242] Matching for: Mathias Antonsen Normann (21-22)

[243] Matching for: Kepa Arrizabalaga Revuelta (21-22)

[244] Matching for: Tanguy NDombele (21-22)

[245] Matching for: Zackary Steffen (21-22)

[246] Matching for: Nicolas N'Koulou (21-22)

[247] Matching for: James Mcatee (21-22)

[248] Matching for: Kouassi Ryan Sessegnon (21-22)

[249] Matching for: Philippe Coutinho (21-22)

[250] Matching for: Vitaliy Mykolenko (21-22)

[251] Matching for: Pedro Neto (21-22)

[252] Matching for: Yann Valery (21-22)

[253] Matching for: Mahmoud Hassan (21-22)

[254] Matching for: Moises Caicedo (21-22)

[255] Matching for: Gabriel Teodoro Martinelli Silva (22-23)

[256] Matching for: Martin Odegaard (22-23)

[257] Matching for: Ben White (22-23)

[258] Matching for: Edward Nketiah (22-23)

[259] Matching for: Addji Keaninkin Marc-Israel Guehi (22-23)

[260] Matching for: Cheick Oumar Doucoure (22-23)

[261] Matching for: Matthew Cash (22-23)

[262] Matching for: Philippe Coutinho (22-23)

[263] Matching for: Emiliano Buendía (22-23)

[264] Matching for: Jefferson Lerma (22-23)

[265] Matching for: Emiliano Martinez (22-23)

[266] Matching for: Rúben Gonçalo Silva Nascimento Vinagre (22-23)

[267] Matching for: Marc Cucurella (22-23)

[268] Matching for: Vitaliy Mykolenko (22-23)

[269] Matching for: Bamidele Alli (22-23)

[270] Matching for: Benjamin Chilwell (22-23)

[271] Matching for: Roberto Firmino Barbosa de Oliveira (22-23)

[272] Matching for: Darwin Núñez (22-23)

[273] Matching for: Aleksandar Mitrovic (22-23)

[274] Matching for: Bobby DeCordova-Reid (22-23)

[275] Matching for: Oluwatosin Adarabioyo (22-23)

[276] Matching for: Andreas Pereira (22-23)

[277] Matching for: Fabio Carvalho (22-23)

[278] Matching for: João Maria Lobo Alves Palhinha Gonçalves (22-23)

[279] Matching for: Rodrigo Moreno Machado (22-23)

[280] Matching for: Diego Javier Llorente Ríos (22-23)

[281] Matching for: Marc Roca (22-23)

[282] Matching for: José Pedro Malheiro de Sá (22-23)

[283] Matching for: Hee-Chan Hwang (22-23)

[284] Matching for: Daniel Podence (22-23)

[285] Matching for: Rayan Ait Nouri (22-23)

[286] Matching for: Pedro Neto (22-23)

[287] Matching for: Rúben Diogo da Silva Neves (22-23)

[288] Matching for: Halil Dervisoglu (22-23)

[289] Matching for: Christian Norgaard (22-23)

[290] Matching for: Pelenda Joshua Dasilva (22-23)

[291] Matching for: Onyinye Wilfred Ndidi (22-23)

[292] Matching for: Joseph Willock (22-23)

[293] Matching for: Miguel Almirón (22-23)

[294] Matching for: Yann Valery (22-23)

[295] Matching for: Ivan Perisic (22-23)

[296] Matching for: Heung-Min Son (22-23)

[297] Matching for: Emerson Aparecido Leite de Souza Junior (22-23)

[298] Matching for: Oriol Romeu (22-23)

[299] Matching for: Romeo Lavia (22-23)

[300] Matching for: Kouassi Ryan Sessegnon (22-23)

[301] Matching for: Joe Aribo (22-23)

[302] Matching for: José Diogo Dalot Teixeira (22-23)

[303] Matching for: Robert Sanchez (22-23)

[304] Matching for: Bruno Miguel Borges Fernandes (22-23)

[305] Matching for: Alejandro Garnacho Ferreyra (22-23)

[306] Matching for: David De Gea (22-23)

[307] Matching for: Moises Caicedo (22-23)

[308] Matching for: Solomon March (22-23)

[309] Matching for: Pablo Fornals (22-23)

[310] Matching for: Rúben Santos Gato Alves Dias (22-23)

[311] Matching for: Said Benrahma (22-23)

[312] Matching for: João Pedro Cavaco Cancelo (22-23)

[313] Matching for: Ilkay Gundogan (22-23)

[314] Matching for: Rodrigo Hernández Cascante (22-23)

[315] Matching for: Bernardo Mota Veiga de Carvalho e Silva (22-23)

[316] Matching for: Emile Smith-Rowe (22-23)

[317] Matching for: Amadou Mvom Onana (22-23)

[318] Matching for: Raphael Varane (22-23)

[319] Matching for: Mads Roerslev (22-23)

[320] Matching for: Carlos Miguel Ribeiro Dias (22-23)

[321] Matching for: Mohammed Elyounoussi (22-23)

[322] Matching for: Armel Bella Kotchap (22-23)

[323] Matching for: Luis Sinisterra (22-23)

[324] Matching for: Adama Traoré (22-23)

[325] Matching for: Nelson Semedo (22-23)

[326] Matching for: Lyanco Evangelista Silveira Neves Vojnovic (22-23)

[327] Matching for: Ayoze Pérez Gutiérrez (22-23)

[328] Matching for: Raul Alonso Jimenez Rodriguez (22-23)

[329] Matching for: João Moutinho (22-23)

[330] Matching for: Jan-Paul van Hecke (22-23)

[331] Matching for: Emiliano Marcondes Camargo Hansen (22-23)

[332] Matching for: Emmanuel Bonaventure Dennis (22-23)

[333] Matching for: Carlos Henrique Jose Francisco Venancio (22-23)

[334] Matching for: Diogo José Teixeira da Silva (22-23)

[335] Matching for: Fábio Daniel Vieira (22-23)

[336] Matching for: Willian Borges Da Silva (22-23)

[337] Matching for: Carlos Vinicius Alves Morais (22-23)

[338] Matching for: Hamed Traore (22-23)

[339] Matching for: Kepa Arrizabalaga Revuelta (22-23)

[340] Matching for: Junior Firpo (22-23)

[341] Matching for: Bertrand Traore (22-23)

[342] Matching for: Ricardo Domingos Barbosa Pereira (22-23)

[343] Matching for: Hugo Bueno (22-23)

[344] Matching for: Ebere Paul Onuachu (22-23)

[345] Matching for: Javier Manquillo (22-23)

[346] Matching for: Marcus Vinícius Oliveira Alencar (22-23)

[347] Matching for: Jeremy Sarmiento (22-23)

[348] Matching for: Asmir Begovic (22-23)

[349] Matching for: Victor Nilsson-Lindelof (22-23)

[350] Matching for: Facundo Pellistri (22-23)

[351] Matching for: Degnand Wilfried Gnonto (22-23)

[352] Matching for: Sergi Canos (22-23)

[353] Matching for: Bryan Gil (22-23)

[354] Matching for: Cedric Ricardo Alves Soares (22-23)

[355] Matching for: Caglar Söyüncü (22-23)

[356] Matching for: Pape Sarr (22-23)

[357] Matching for: Matias Viña (22-23)

[358] Matching for: Arnaut Danjuma Groeneveld (22-23)

[359] Matching for: Valentino Livramento (22-23)

[360] Matching for: Benson Manuel (23-24)

[361] Matching for: Rodrigo Hernández Cascante (23-24)

[362] Matching for: Mateo Kovacic (23-24)

[363] Matching for: Bernardo Mota Veiga de Carvalho e Silva (23-24)

[364] Matching for: Ameen Al Dakhil (23-24)

[365] Matching for: James Mcatee (23-24)

[366] Matching for: Victor Alexander da Silva (23-24)

[367] Matching for: Said Benrahma (23-24)

[368] Matching for: Tomas Soucek (23-24)

[369] Matching for: Vladimir Coufal (23-24)

[370] Matching for: Pablo Fornals (23-24)

[371] Matching for: Maximillian Aarons (23-24)

[372] Matching for: Edward Nketiah (23-24)

[373] Matching for: Ola Aina (23-24)

[374] Matching for: Martin Odegaard (23-24)

[375] Matching for: Ben White (23-24)

[376] Matching for: Gabriel Teodoro Martinelli Silva (23-24)

[377] Matching for: Amarii Bell (23-24)

[378] Matching for: Jan-Paul van Hecke (23-24)

[379] Matching for: Mads Andersen (23-24)

[380] Matching for: Issa Kabore (23-24)

[381] Matching for: Ryan John Giles (23-24)

[382] Matching for: Solomon March (23-24)

[383] Matching for: Amadou Mvom Onana (23-24)

[384] Matching for: Andreas Pereira (23-24)

[385] Matching for: Sasa Lukic (23-24)

[386] Matching for: Willian Borges Da Silva (23-24)

[387] Matching for: Aleksandar Mitrovic (23-24)

[388] Matching for: Raul Alonso Jimenez Rodriguez (23-24)

[389] Matching for: Bobby DeCordova-Reid (23-24)

[390] Matching for: Philippe Coutinho (23-24)

[391] Matching for: Miguel Almirón (23-24)

[392] Matching for: Emiliano Martinez (23-24)

[393] Matching for: Matthew Cash (23-24)

[394] Matching for: Cheick Oumar Doucoure (23-24)

[395] Matching for: Vinicius de Souza Costa (23-24)

[396] Matching for: Addji Keaninkin Marc-Israel Guehi (23-24)

[397] Matching for: Anis Ben Slimane (23-24)

[398] Matching for: Jefferson Lerma (23-24)

[399] Matching for: Anel Ahmedhodzic (23-24)

[400] Matching for: Pape Sarr (23-24)

[401] Matching for: Christian Norgaard (23-24)

[402] Matching for: Mads Roerslev (23-24)

[403] Matching for: Emerson Aparecido Leite de Souza Junior (23-24)

[404] Matching for: Iyenoma Destiny Udogie (23-24)

[405] Matching for: Heung-Min Son (23-24)

[406] Matching for: Ivan Perisic (23-24)

[407] Matching for: Darwin Núñez (23-24)

[408] Matching for: Benjamin Chilwell (23-24)

[409] Matching for: Robert Sanchez (23-24)

[410] Matching for: Diogo José Teixeira da Silva (23-24)

[411] Matching for: Rayan Ait Nouri (23-24)

[412] Matching for: Bruno Miguel Borges Fernandes (23-24)

[413] Matching for: Hugo Bueno (23-24)

[414] Matching for: José Pedro Malheiro de Sá (23-24)

[415] Matching for: Victor Nilsson-Lindelof (23-24)

[416] Matching for: Carlos Henrique Jose Francisco Venancio (23-24)

[417] Matching for: Fabio Daniel Soares Silva (23-24)


In [33]:
matches_df[matches_df['match_indicator'] == 0]

,name1,name2,season,score,match_indicator
88,Diogo José Teixeira da Silva,Danilo Luiz da Silva,19-20,58.333333,0
116,Roberto Jiménez,Roberto Jimenez Gago,19-20,80.000000,0
135,Ivan Cavaleiro,Yan Valery,20-21,66.666667,0
142,Helder Costa,Oliver Casey,20-21,50.000000,0
149,Semi Ajayi,Faustino Anjorin,20-21,46.153846,0
160,Raul Alonso Jimenez Rodriguez,Roberto Jimenez Gago,20-21,53.061224,0
167,Diogo José Teixeira da Silva,José Diogo Dalot Teixeira,20-21,60.377358,0
168,Thiago Emiliano da Silva,Thiago Thiago,20-21,54.054054,0
194,Addji Keaninkin Marc-Israel Guehi,Adrián San Miguel del Castillo,21-22,44.444444,0
198,João Moutinho,Josh Martin,21-22,58.333333,0
202,Raul Alonso Jimenez Rodriguez,James Rodríguez,21-22,54.545455,0
207,Helder Costa,Dara Costelloe,21-22,53.846154,0
233,Mohamed Elneny,Mohamed Elyounoussi,21-22,66.666667,0
235,Bryan Gil,Ryan Giles,21-22,84.210526,0
258,Addji Keaninkin Marc-Israel Guehi,Adrián San Miguel del Castillo,22-23,44.444444,0
264,Emiliano Martinez,Emiliano Marcondes,22-23,80.000000,0
276,Fabio Carvalho,Fabio Silva,22-23,64.000000,0
282,Hee-Chan Hwang,Ethan Wady,22-23,58.333333,0
327,Raul Alonso Jimenez Rodriguez,Braian Ojeda Rodríguez,22-23,50.980392,0
359,Benson Manuel,Jenson Metcalfe,23-24,64.285714,0
387,Raul Alonso Jimenez Rodriguez,Braian Ojeda Rodríguez,23-24,50.980392,0
391,Emiliano Martinez,Emiliano Marcondes,23-24,80.000000,0
395,Addji Keaninkin Marc-Israel Guehi,Adrián San Miguel del Castillo,23-24,44.444444,0
416,Fabio Daniel Soares Silva,Gabriel Martinelli Silva,23-24,61.224490,0
445,Bryan Gil,Ryan Giles,23-24,84.210526,0
484,Carlos Alcaraz,Carlos Alcaraz Durán,24-25,82.352941,0
499,Addji Keaninkin Marc-Israel Guehi,Adrian Mazilu,24-25,47.826087,0
505,Marc Guiu,Marc Guéhi,24-25,84.210526,0
525,Wataru Endo,Amara Nallo,24-25,54.545455,0
547,Takehiro Tomiyasu,Kevin Mbabu,24-25,50.000000,0

In [39]:
numbers = [86, 116, 168, 473]

for i in numbers:
    print(matches_df.iloc[i])
    print("---------------------------------------------------")

name1              Raul Alonso Jimenez Rodriguez
name2                       Roberto Jimenez Gago
season                                     19-20
score                                  53.061224
match_indicator                                1
Name: 86, dtype: object
---------------------------------------------------
name1                   Roberto Jiménez
name2              Roberto Jimenez Gago
season                            19-20
score                              80.0
match_indicator                       0
Name: 116, dtype: object
---------------------------------------------------
name1              Thiago Emiliano da Silva
name2                         Thiago Thiago
season                                20-21
score                             54.054054
match_indicator                           0
Name: 168, dtype: object
---------------------------------------------------
name1              Kaoru Mitoma
name2                Sékou Mara
season                    24-25
score                 54.545455
match_indicator               1
Name: 473, dtype: object
---------------------------------------------------

In [40]:
matches_df.to_csv('../data/player_price_matches.csv', index=False)

In [74]:
from difflib import SequenceMatcher
import pandas as pd

def similarity(a, b):
    return SequenceMatcher(None, a.lower(), b.lower()).ratio() * 100

def top_matches(index, left, right, top_n=10):
    name1, season1 = left.iloc[index][["full_name", "season"]]
    results = []

    for name2, season2 in right[["full_name", "season"]].itertuples(index=False):
        if season1 != season2:
            continue
        score = similarity(name1, name2)
        results.append({"name1": name1, "name2": name2, "season": season1, "score": score})

    results_df = pd.DataFrame(results)
    top_df = results_df.sort_values(by="score", ascending=False).head(top_n)
    return top_df

numbers = [88, 116, 135, 142, 149, 160, 167, 168, 194, 198, 202, 207, 233, 235, 258, 264, 276, 282, 327, 359, 387, 391, 395, 416, 445, 473, 484, 499, 505, 525, 547]

for number in numbers:
    print("---------------------------------------------------")
    print(top_matches(number, left, right))
    print("---------------------------------------------------")

---------------------------------------------------
                            name1                             name2 season  \
45   Diogo José Teixeira da Silva              Danilo Luiz da Silva  19-20
52   Diogo José Teixeira da Silva                        Diogo Jota  19-20
27   Diogo José Teixeira da Silva            Bernardo Costa Da Rosa  19-20
7    Diogo José Teixeira da Silva  Alexandre Nascimento Costa Silva  19-20
70   Diogo José Teixeira da Silva           Heurelho da Silva Gomes  19-20
96   Diogo José Teixeira da Silva    José Ignacio Peleteiro Romallo  19-20
37   Diogo José Teixeira da Silva                  Christian Saydee  19-20
145  Diogo José Teixeira da Silva                 Oriol Romeu Vidal  19-20
74   Diogo José Teixeira da Silva                      Ismaïla Sarr  19-20
1    Diogo José Teixeira da Silva               Adalberto Peñaranda  19-20

         score
45   58.333333
52   52.631579
27   52.000000
7    46.666667
70   39.215686
96   37.931034
37   36.363636
145  35.555556
74   35.000000
1    34.042553
---------------------------------------------------
---------------------------------------------------
               name1                              name2 season      score
166  Roberto Jiménez               Roberto Jimenez Gago  19-20  80.000000
165  Roberto Jiménez                    Roberto Firmino  19-20  73.333333
158  Roberto Jiménez                       Raúl Jiménez  19-20  66.666667
163  Roberto Jiménez                      Robert Elliot  19-20  50.000000
164  Roberto Jiménez  Robert Kenedy Nunes do Nascimento  19-20  45.833333
95   Roberto Jiménez      José Heriberto Izquierdo Mena  19-20  45.454545
167  Roberto Jiménez                  Rodrigo Hernandez  19-20  43.750000
147  Roberto Jiménez                      Owen Otasowie  19-20  42.857143
24   Roberto Jiménez                     Beni Baningime  19-20  41.379310
1    Roberto Jiménez                Adalberto Peñaranda  19-20  41.176471
---------------------------------------------------
---------------------------------------------------
              name1                               name2 season      score
240  Ivan Cavaleiro                          Yan Valery  20-21  66.666667
86   Ivan Cavaleiro  Ivan Ricardo Neves Abreu Cavaleiro  20-21  58.333333
56   Ivan Cavaleiro                        Elia Caprile  20-21  53.846154
6    Ivan Cavaleiro                        Albian Ajeti  20-21  53.846154
98   Ivan Cavaleiro                   Jean Michaël Seri  20-21  51.612903
190  Ivan Cavaleiro                      Rolando Aarons  20-21  50.000000
175  Ivan Cavaleiro                 Patrick van Aanholt  20-21  48.484848
155  Ivan Cavaleiro                     Meritan Shabani  20-21  48.275862
192  Ivan Cavaleiro                         Ryan Astley  20-21  48.000000
169  Ivan Cavaleiro                Nélson Cabral Semedo  20-21  47.058824
---------------------------------------------------
---------------------------------------------------
            name1                                   name2 season      score
170  Helder Costa                            Oliver Casey  20-21  50.000000
228  Helder Costa                           Tyler Onyango  20-21  48.000000
70   Helder Costa                          Frederik Alves  20-21  46.153846
55   Helder Costa                              Diogo Jota  20-21  45.454545
157  Helder Costa                         Michael Verrips  20-21  44.444444
82   Helder Costa  Hélder Wander Sousa de Azevedo e Costa  20-21  44.000000
64   Helder Costa                            Felix Nmecha  20-21  41.666667
171  Helder Costa                            Oliver Skipp  20-21  41.666667
56   Helder Costa                            Elia Caprile  20-21  41.666667
210  Helder Costa                       Stephen Henderson  20-21  41.379310
---------------------------------------------------
---------------------------------------------------
          name1                                name2 season      score
63   Semi Ajayi                     Faustino Anjorin  20-21  46.153846
227  Semi Ajayi                     Tosin Adarabioyo  20-21  46.153846
34   Semi Ajayi                         Cheikh Diaby  20-21  45.454545
56   Semi Ajayi                         Elia Caprile  20-21  45.454545
6    Semi Ajayi                         Albian Ajeti  20-21  45.454545
172  Semi Ajayi  Oluwasemilogo Adesewo Ibidapo Ajayi  20-21  44.444444
101  Semi Ajayi                    Jesurun Rak-Sakyi  20-21  44.444444
145  Semi Ajayi                        Matija Sarkic  20-21  43.478261
202  Semi Ajayi                        Sergio Agüero  20-21  43.478261
80   Semi Ajayi                       Henri Lansbury  20-21  41.666667
---------------------------------------------------
---------------------------------------------------
                             name1                      name2 season  \
187  Raul Alonso Jimenez Rodriguez       Roberto Jimenez Gago  20-21
180  Raul Alonso Jimenez Rodriguez               Raúl Jiménez  20-21
174  Raul Alonso Jimenez Rodriguez  Pablo Hernández Domínguez  20-21
28   Raul Alonso Jimenez Rodriguez           Brandon Pierrick  20-21
143  Raul Alonso Jimenez Rodriguez             Mateusz Bogusz  20-21
136  Raul Alonso Jimenez Rodriguez             Mace Goodridge  20-21
118  Raul Alonso Jimenez Rodriguez                Karlo Ziger  20-21
48   Raul Alonso Jimenez Rodriguez     Daniel Castelo Podence  20-21
29   Raul Alonso Jimenez Rodriguez  Bruno André Cavaco Jordao  20-21
176  Raul Alonso Jimenez Rodriguez            Paulo Gazzaniga  20-21

         score
187  53.061224
180  48.780488
174  48.148148
28   44.444444
143  41.860465
136  41.860465
118  40.000000
48   39.215686
29   37.037037
176  36.363636
---------------------------------------------------
---------------------------------------------------
                            name1                                name2 season  \
110  Diogo José Teixeira da Silva            José Diogo Dalot Teixeira  20-21
55   Diogo José Teixeira da Silva                           Diogo Jota  20-21
3    Diogo José Teixeira da Silva                         Adrien Silva  20-21
172  Diogo José Teixeira da Silva  Oluwasemilogo Adesewo Ibidapo Ajayi  20-21
60   Diogo José Teixeira da Silva                          Fabio Silva  20-21
84   Diogo José Teixeira da Silva                     Indiana Vassilev  20-21
107  Diogo José Teixeira da Silva                        Jordan Hugill  20-21
112  Diogo José Teixeira da Silva                       José Izquierdo  20-21
54   Diogo José Teixeira da Silva                       Diego Llorente  20-21
231  Diogo José Teixeira da Silva                       Vitor Ferreira  20-21

         score
110  60.377358
55   52.631579
3    45.000000
172  41.269841
60   41.025641
84   40.909091
107  39.024390
112  38.095238
54   38.095238
231  38.095238
---------------------------------------------------
---------------------------------------------------
                        name1               name2 season      score
221  Thiago Emiliano da Silva       Thiago Thiago  20-21  54.054054
84   Thiago Emiliano da Silva    Indiana Vassilev  20-21  50.000000
3    Thiago Emiliano da Silva        Adrien Silva  20-21  50.000000
59   Thiago Emiliano da Silva   Emiliano Martínez  20-21  48.780488
60   Thiago Emiliano da Silva         Fabio Silva  20-21  45.714286
6    Thiago Emiliano da Silva        Albian Ajeti  20-21  44.444444
56   Thiago Emiliano da Silva        Elia Caprile  20-21  44.444444
214  Thiago Emiliano da Silva  Tawanda Maswanhise  20-21  42.857143
239  Thiago Emiliano da Silva      William Saliba  20-21  42.105263
81   Thiago Emiliano da Silva          Hugo Bueno  20-21  41.176471
---------------------------------------------------
---------------------------------------------------
                                 name1                           name2 season  \
4    Addji Keaninkin Marc-Israel Guehi  Adrián San Miguel del Castillo  21-22
142  Addji Keaninkin Marc-Israel Guehi                      Marc Guéhi  21-22
23   Addji Keaninkin Marc-Israel Guehi          Bailey Peacock-Farrell  21-22
126  Addji Keaninkin Marc-Israel Guehi               Kepa Arrizabalaga  21-22
72   Addji Keaninkin Marc-Israel Guehi                 Fernando Marçal  21-22
73   Addji Keaninkin Marc-Israel Guehi                 Filip Marschall  21-22
15   Addji Keaninkin Marc-Israel Guehi                 Anthony Mancini  21-22
1    Addji Keaninkin Marc-Israel Guehi                      Abu Kamara  21-22
27   Addji Keaninkin Marc-Israel Guehi               Benjamin Chrisene  21-22
129  Addji Keaninkin Marc-Israel Guehi         Konstantinos Mavropanos  21-22

         score
4    44.444444
142  41.860465
23   40.000000
126  40.000000
72   37.500000
73   37.500000
15   37.500000
1    37.209302
27   36.000000
129  35.714286
---------------------------------------------------
---------------------------------------------------
             name1                             name2 season      score
115  João Moutinho                       Josh Martin  21-22  58.333333
118  João Moutinho  João Filipe Iria Santos Moutinho  21-22  57.777778
119  João Moutinho                     João Virgínia  21-22  53.846154
214  João Moutinho                    Rodrigo Moreno  21-22  51.851852
44   João Moutinho                   Conor Hourihane  21-22  50.000000
212  João Moutinho                   Roberto Firmino  21-22  50.000000
187  João Moutinho                  Omari Hutchinson  21-22  48.275862
136  João Moutinho                     Louie Moulden  21-22  46.153846
109  João Moutinho                Jonathan Tomkinson  21-22  45.161290
33   João Moutinho                    Brandon Austin  21-22  44.444444
---------------------------------------------------
---------------------------------------------------
                             name1                                     name2  \
100  Raul Alonso Jimenez Rodriguez                           James Rodríguez
204  Raul Alonso Jimenez Rodriguez                              Raúl Jiménez
193  Raul Alonso Jimenez Rodriguez                 Pablo Hernández Domínguez
120  Raul Alonso Jimenez Rodriguez              Juan Camilo Hernández Suárez
121  Raul Alonso Jimenez Rodriguez                           Julian Jeanvier
46   Raul Alonso Jimenez Rodriguez                    Daniel Castelo Podence
218  Raul Alonso Jimenez Rodriguez                             Ryan Alebiosu
76   Raul Alonso Jimenez Rodriguez  Francisco Machado Mota de Castro Trincão
34   Raul Alonso Jimenez Rodriguez                 Bruno André Cavaco Jordão
212  Raul Alonso Jimenez Rodriguez                           Roberto Firmino

    season      score
100  21-22  54.545455
204  21-22  48.780488
193  21-22  48.148148
120  21-22  45.614035
121  21-22  40.909091
46   21-22  39.215686
218  21-22  38.095238
76   21-22  37.681159
34   21-22  37.037037
212  21-22  36.363636
---------------------------------------------------
---------------------------------------------------
            name1                                   name2 season      score
48   Helder Costa                          Dara Costelloe  21-22  53.846154
63   Helder Costa                         Ellery Balcombe  21-22  51.851852
157  Helder Costa                       Matthew Longstaff  21-22  48.275862
236  Helder Costa                           Thierry Small  21-22  48.000000
176  Helder Costa                      Nathaniel Chalobah  21-22  46.666667
77   Helder Costa                          Frederik Alves  21-22  46.153846
52   Helder Costa                          Dean Henderson  21-22  46.153846
57   Helder Costa                              Diogo Jota  21-22  45.454545
64   Helder Costa                         Elliot Anderson  21-22  44.444444
90   Helder Costa  Hélder Wander Sousa de Azevedo e Costa  21-22  44.000000
---------------------------------------------------
---------------------------------------------------
              name1                          name2 season      score
170  Mohamed Elneny            Mohamed Elyounoussi  21-22  66.666667
171  Mohamed Elneny  Mohamed Naser El Sayed Elneny  21-22  65.116279
114  Mohamed Elneny                    Josh Feeney  21-22  56.000000
181  Mohamed Elneny                   Nohan Kenneh  21-22  46.153846
151  Mohamed Elneny                   Martin Kelly  21-22  46.153846
102  Mohamed Elneny                   Jamie Bowden  21-22  46.153846
7    Mohamed Elneny                   Alfie Devine  21-22  46.153846
98   Mohamed Elneny                   James McAtee  21-22  46.153846
162  Mohamed Elneny                 Mazeed Ogungbo  21-22  42.857143
24   Mohamed Elneny                     Ben Nelson  21-22  41.666667
---------------------------------------------------
---------------------------------------------------
         name1                  name2 season      score
219  Bryan Gil             Ryan Giles  21-22  84.210526
110  Bryan Gil          Jordan Hugill  21-22  63.636364
35   Bryan Gil  Bryan Gil Salvatierra  21-22  60.000000
31   Bryan Gil           Björn Engels  21-22  57.142857
218  Bryan Gil          Ryan Alebiosu  21-22  54.545455
25   Bryan Gil             Ben Wilmot  21-22  52.631579
259  Bryan Gil             Yan Valery  21-22  52.631579
33   Bryan Gil         Brandon Austin  21-22  52.173913
220  Bryan Gil         Ryan Sessegnon  21-22  52.173913
3    Bryan Gil           Adrian Blake  21-22  47.619048
---------------------------------------------------
---------------------------------------------------
                                 name1                           name2 season  \
1    Addji Keaninkin Marc-Israel Guehi  Adrián San Miguel del Castillo  22-23
19   Addji Keaninkin Marc-Israel Guehi                  Anwar El Ghazi  22-23
95   Addji Keaninkin Marc-Israel Guehi        Gabriel Martinelli Silva  22-23
195  Addji Keaninkin Marc-Israel Guehi                      Marc Guéhi  22-23
59   Addji Keaninkin Marc-Israel Guehi                Daniel Adu-Adjei  22-23
265  Addji Keaninkin Marc-Israel Guehi          Rodrigo Muniz Carvalho  22-23
164  Addji Keaninkin Marc-Israel Guehi               Kepa Arrizabalaga  22-23
36   Addji Keaninkin Marc-Israel Guehi          Braian Ojeda Rodríguez  22-23
129  Addji Keaninkin Marc-Israel Guehi         Javier Manquillo Gaitán  22-23
112  Addji Keaninkin Marc-Israel Guehi                   Imari Samuels  22-23

         score
1    44.444444
19   42.553191
95   42.105263
195  41.860465
59   40.816327
265  40.000000
164  40.000000
36   40.000000
129  39.285714
112  39.130435
---------------------------------------------------
---------------------------------------------------
                 name1                     name2 season      score
79   Emiliano Martinez        Emiliano Marcondes  22-23  80.000000
80   Emiliano Martinez  Emiliano Martínez Romero  22-23  78.048780
78   Emiliano Martinez    Emiliano Buendía Stati  22-23  61.538462
254  Emiliano Martinez             Remi Matthews  22-23  53.333333
37   Emiliano Martinez            Brandon Austin  22-23  51.612903
193  Emiliano Martinez               Malang Sarr  22-23  50.000000
134  Emiliano Martinez  Jeremy Sarmiento Morante  22-23  48.780488
95   Emiliano Martinez  Gabriel Martinelli Silva  22-23  48.780488
163  Emiliano Martinez              Keinan Davis  22-23  48.275862
157  Emiliano Martinez              Kaelan Casey  22-23  48.275862
---------------------------------------------------
---------------------------------------------------
              name1                           name2 season      score
86   Fabio Carvalho                     Fabio Silva  22-23  64.000000
265  Fabio Carvalho          Rodrigo Muniz Carvalho  22-23  61.111111
94   Fabio Carvalho  Fábio Freitas Gouveia Carvalho  22-23  59.090909
241  Fabio Carvalho               Pablo Marí Villar  22-23  51.612903
2    Fabio Carvalho              Alejandro Garnacho  22-23  50.000000
295  Fabio Carvalho                  Tayo Adaramola  22-23  50.000000
89   Fabio Carvalho                 Filip Marschall  22-23  48.275862
319  Fabio Carvalho                 Willy Caballero  22-23  48.275862
234  Fabio Carvalho            Nélson Cabral Semedo  22-23  47.058824
150  Fabio Carvalho                    João Cancelo  22-23  46.153846
---------------------------------------------------
---------------------------------------------------
              name1             name2 season      score
84   Hee-Chan Hwang        Ethan Wady  22-23  58.333333
110  Hee-Chan Hwang    Hwang Hee-chan  22-23  57.142857
83   Hee-Chan Hwang      Ethan Ampadu  22-23  46.153846
146  Hee-Chan Hwang      Joseph Anang  22-23  46.153846
144  Hee-Chan Hwang    Jonathan Panzo  22-23  42.857143
296  Hee-Chan Hwang   Terence Kongolo  22-23  41.379310
280  Hee-Chan Hwang   Sebastian Revan  22-23  41.379310
292  Hee-Chan Hwang   Steven Bergwijn  22-23  41.379310
188  Hee-Chan Hwang       Luke Plange  22-23  40.000000
219  Hee-Chan Hwang  Michael Olakigbe  22-23  40.000000
---------------------------------------------------
---------------------------------------------------
                             name1                     name2 season      score
36   Raul Alonso Jimenez Rodriguez    Braian Ojeda Rodríguez  22-23  50.980392
252  Raul Alonso Jimenez Rodriguez              Raúl Jiménez  22-23  48.780488
80   Raul Alonso Jimenez Rodriguez  Emiliano Martínez Romero  22-23  45.283019
60   Raul Alonso Jimenez Rodriguez    Daniel Castelo Podence  22-23  39.215686
156  Raul Alonso Jimenez Rodriguez              Kaden Rodney  22-23  39.024390
126  Raul Alonso Jimenez Rodriguez        Jan Paul van Hecke  22-23  38.297872
198  Raul Alonso Jimenez Rodriguez             Marcos Alonso  22-23  38.095238
23   Raul Alonso Jimenez Rodriguez            Arnaut Danjuma  22-23  37.209302
266  Raul Alonso Jimenez Rodriguez            Romaine Mundle  22-23  37.209302
221  Raul Alonso Jimenez Rodriguez            Mohamed Dräger  22-23  37.209302
---------------------------------------------------
---------------------------------------------------
             name1               name2 season      score
179  Benson Manuel     Jenson Metcalfe  23-24  64.285714
386  Benson Manuel     Yerson Mosquera  23-24  57.142857
26   Benson Manuel        Anis Slimane  23-24  56.000000
107  Benson Manuel           Enes Ünal  23-24  54.545455
51   Benson Manuel      Brandon Austin  23-24  51.851852
104  Benson Manuel  Emiliano Marcondes  23-24  51.612903
37   Benson Manuel         Ben Pearson  23-24  50.000000
36   Benson Manuel         Ben Jackson  23-24  50.000000
39   Benson Manuel     Benjamin Arthur  23-24  50.000000
221  Benson Manuel         Kevin Mbabu  23-24  50.000000
---------------------------------------------------
---------------------------------------------------
                             name1                      name2 season  \
49   Raul Alonso Jimenez Rodriguez     Braian Ojeda Rodríguez  23-24
62   Raul Alonso Jimenez Rodriguez        Carlos Mendes Gomes  23-24
307  Raul Alonso Jimenez Rodriguez               Raúl Jiménez  23-24
105  Raul Alonso Jimenez Rodriguez   Emiliano Martínez Romero  23-24
123  Raul Alonso Jimenez Rodriguez       Franco Umeh-Chibueze  23-24
255  Raul Alonso Jimenez Rodriguez    Manuel Benson Hedilazio  23-24
329  Raul Alonso Jimenez Rodriguez             Samuel Bastien  23-24
390  Raul Alonso Jimenez Rodriguez  Álvaro Fernández Carreras  23-24
25   Raul Alonso Jimenez Rodriguez           Anel Ahmedhodžić  23-24
74   Raul Alonso Jimenez Rodriguez     Daniel Castelo Podence  23-24

         score
49   50.980392
62   50.000000
307  48.780488
105  45.283019
123  44.897959
255  42.307692
329  41.860465
390  40.740741
25   40.000000
74   39.215686
---------------------------------------------------
---------------------------------------------------
                 name1                       name2 season      score

In [75]:
match_numbers = [1, 0, 1, 5, 5, 1, 1, 0, 1, 1, 1, 9, 1, 2, 3, 1, 2, 1, 1, 21, 2, 1, 2, 1, 1, 1, 0, 2, 1, 0, 2]

print(numbers[7])
print(numbers[19])
print(top_matches(168, left, right, 30))
print(top_matches(359, left, right, 30))

168
359
                        name1                                name2 season  \
221  Thiago Emiliano da Silva                        Thiago Thiago  20-21
84   Thiago Emiliano da Silva                     Indiana Vassilev  20-21
3    Thiago Emiliano da Silva                         Adrien Silva  20-21
59   Thiago Emiliano da Silva                    Emiliano Martínez  20-21
60   Thiago Emiliano da Silva                          Fabio Silva  20-21
6    Thiago Emiliano da Silva                         Albian Ajeti  20-21
56   Thiago Emiliano da Silva                         Elia Caprile  20-21
214  Thiago Emiliano da Silva                   Tawanda Maswanhise  20-21
239  Thiago Emiliano da Silva                       William Saliba  20-21
81   Thiago Emiliano da Silva                           Hugo Bueno  20-21
17   Thiago Emiliano da Silva                      Anthony Mancini  20-21
230  Thiago Emiliano da Silva                      Victor Lindelöf  20-21
62   Thiago Emiliano da Silva                    Facundo Pellistri  20-21
98   Thiago Emiliano da Silva                    Jean Michaël Seri  20-21
173  Thiago Emiliano da Silva                    Oriol Romeu Vidal  20-21
188  Thiago Emiliano da Silva                    Rodrigo Hernandez  20-21
222  Thiago Emiliano da Silva                        Thomas McGill  20-21
119  Thiago Emiliano da Silva                        Kelland Watts  20-21
220  Thiago Emiliano da Silva             Thanawat Suengchitthawon  20-21
172  Thiago Emiliano da Silva  Oluwasemilogo Adesewo Ibidapo Ajayi  20-21
111  Thiago Emiliano da Silva       José Ignacio Peleteiro Romallo  20-21
36   Thiago Emiliano da Silva                       Christian Atsu  20-21
80   Thiago Emiliano da Silva                       Henri Lansbury  20-21
154  Thiago Emiliano da Silva                       Mbwana Samatta  20-21
207  Thiago Emiliano da Silva                       Sofiane Boufal  20-21
79   Thiago Emiliano da Silva                       Harvey Elliott  20-21
189  Thiago Emiliano da Silva                       Rodrigo Moreno  20-21
110  Thiago Emiliano da Silva            José Diogo Dalot Teixeira  20-21
2    Thiago Emiliano da Silva                      Ademipo Odubeko  20-21
186  Thiago Emiliano da Silva                      Roberto Firmino  20-21

         score
221  54.054054
84   50.000000
3    50.000000
59   48.780488
60   45.714286
6    44.444444
56   44.444444
214  42.857143
239  42.105263
81   41.176471
17   41.025641
230  41.025641
62   39.024390
98   39.024390
173  39.024390
188  39.024390
222  37.837838
119  37.837838
220  37.500000
172  37.288136
111  37.037037
36   36.842105
80   36.842105
154  36.842105
207  36.842105
79   36.842105
189  36.842105
110  36.734694
2    35.897436
186  35.897436
             name1                     name2 season      score
179  Benson Manuel           Jenson Metcalfe  23-24  64.285714
386  Benson Manuel           Yerson Mosquera  23-24  57.142857
26   Benson Manuel              Anis Slimane  23-24  56.000000
107  Benson Manuel                 Enes Ünal  23-24  54.545455
51   Benson Manuel            Brandon Austin  23-24  51.851852
104  Benson Manuel        Emiliano Marcondes  23-24  51.612903
37   Benson Manuel               Ben Pearson  23-24  50.000000
36   Benson Manuel               Ben Jackson  23-24  50.000000
39   Benson Manuel           Benjamin Arthur  23-24  50.000000
221  Benson Manuel               Kevin Mbabu  23-24  50.000000
192  Benson Manuel               John McAtee  23-24  50.000000
108  Benson Manuel               Enock Agyei  23-24  50.000000
106  Benson Manuel           Emmanuel Dennis  23-24  50.000000
373  Benson Manuel          Vincent Angelini  23-24  48.275862
34   Benson Manuel              Ben Chilwell  23-24  48.000000
206  Benson Manuel              João Cancelo  23-24  48.000000
110  Benson Manuel              Ethan Ampadu  23-24  48.000000
167  Benson Manuel              James McAtee  23-24  48.000000
178  Benson Manuel     Jefferson Lerma Solís  23-24  47.058824
81   Benson Manuel             Denis Franchi  23-24  46.153846
341  Benson Manuel             Son Heung-min  23-24  46.153846
96   Benson Manuel   Edson Álvarez Velázquez  23-24  44.444444
255  Benson Manuel   Manuel Benson Hedilazio  23-24  44.444444
41   Benson Manuel            Benjamin White  23-24  44.444444
299  Benson Manuel       Pablo Fornals Malla  23-24  43.750000
83   Benson Manuel                Dermot Mee  23-24  43.478261
154  Benson Manuel                Ionuț Radu  23-24  43.478261
105  Benson Manuel  Emiliano Martínez Romero  23-24  43.243243
180  Benson Manuel  Jeremy Sarmiento Morante  23-24  43.243243
128  Benson Manuel  Gabriel Martinelli Silva  23-24  43.243243

In [77]:
for idx, match_pos in zip(numbers, match_numbers):
    # Get top matches for this index
    candidates = top_matches(idx, left, right, top_n=(match_pos + 1))
    
    # Pick the specific match position
    chosen = candidates.iloc[match_pos]
    
    # Find and update the original row instead of appending
    mask = (
        (matches_df['name1'] == chosen["name1"]) &
        (matches_df['season'] == chosen["season"])
    )

    if mask.any():
        matches_df.loc[mask, ['name2', 'score', 'match_indicator']] = [
            chosen["name2"], chosen["score"], 1
        ]
    else:
        # If not found (shouldn't happen normally), append as fallback
        matches_df = pd.concat([
            matches_df,
            pd.DataFrame([{
                "name1": chosen["name1"],
                "name2": chosen["name2"],
                "season": chosen["season"],
                "score": chosen["score"],
                "match_indicator": 1
            }])
        ], ignore_index=True)

In [80]:
matches_df = matches_df.loc[matches_df.index <= 571].copy()

In [83]:
matches_df.to_csv('../data/player_price_matches.csv', index=False)

In [1]:
import pandas as pd
matches_df = pd.read_csv('../data/player_price_matches.csv')
matches_df

,name1,name2,season,score,match_indicator
0,Onyinye Wilfred Ndidi,Wilfred Ndidi,17-18,76.470588,1
1,Mesut Ozil,Mesut Özil,17-18,90.000000,1
2,Matthew James,Matty James,17-18,83.333333,1
3,Sergio Aguero,Sergio Agüero,17-18,92.307692,1
4,Francesc Fábregas,Cesc Fàbregas,17-18,80.000000,1
...,...,...,...,...,...
567,Abduqodir Khusanov,Abdukodir Khusanov,24-25,94.444444,1
568,Benjamin Chilwell,Ben Chilwell,24-25,82.758621,1
569,Willian Borges Da Silva,Willian Borges da Silva,24-25,100.000000,1
570,Nasser Yacouba Djiga,Nasser Djiga,24-25,75.000000,1
571,Armel Bella Kotchap,Armel Bella-Kotchap,24-25,94.736842,1

In [15]:
player_data[player_data.initial_cost.isna()].drop_duplicates(subset=['full_name', 'season']).sort_values(by='match_id')

,match_id,nick_name,full_name,pos,team,cost,season,first_appearance,initial_cost
2,918893,Ozil,Mesut Ozil,Midfielder,ARS,0.0,17-18,0,NaN
19,918893,James (Matthew),Matthew James,Midfielder,LEI,0.0,17-18,0,NaN
27,918893,Ndidi,Onyinye Wilfred Ndidi,Midfielder,LEI,4.9,17-18,0,NaN
45,918894,Aguero,Sergio Aguero,Forward,MCI,0.0,17-18,0,NaN
68,918895,Brady,Robert Brady,Midfielder,BUR,0.0,17-18,0,NaN
...,...,...,...,...,...,...,...,...,...
82127,2444696,Khusanov,Abduqodir Khusanov,Defender,MCI,5.5,24-25,0,NaN
82583,2444712,Chilwell,Benjamin Chilwell,Defender,CRY,4.6,24-25,0,NaN
82609,2444713,Willian,Willian Borges Da Silva,Midfielder,FUL,5.0,24-25,0,NaN
82851,2444720,Djiga,Nasser Yacouba Djiga,Defender,WOL,4.5,24-25,0,NaN
83117,2444729,Bella Kotchap,Armel Bella Kotchap,Defender,SOU,3.9,24-25,0,NaN

In [17]:
matches_df_with_cost = matches_df.merge(
    initial_costs,
    left_on=['name2', 'season'],
    right_on=['full_name', 'season'],
    how='left'
)
matches_df_with_cost.drop(columns=['full_name'], inplace=True)
matches_df_with_cost

,name1,name2,season,score,match_indicator,initial_cost
0,Onyinye Wilfred Ndidi,Wilfred Ndidi,17-18,76.470588,1,5.0
1,Mesut Ozil,Mesut Özil,17-18,90.000000,1,9.5
2,Matthew James,Matty James,17-18,83.333333,1,4.5
3,Sergio Aguero,Sergio Agüero,17-18,92.307692,1,11.5
4,Francesc Fábregas,Cesc Fàbregas,17-18,80.000000,1,7.0
...,...,...,...,...,...,...
568,Abduqodir Khusanov,Abdukodir Khusanov,24-25,94.444444,1,5.0
569,Benjamin Chilwell,Ben Chilwell,24-25,82.758621,1,5.0
570,Willian Borges Da Silva,Willian Borges da Silva,24-25,100.000000,1,5.0
571,Nasser Yacouba Djiga,Nasser Djiga,24-25,75.000000,1,4.5
572,Armel Bella Kotchap,Armel Bella-Kotchap,24-25,94.736842,1,4.0

In [19]:
for index, row in  matches_df_with_cost.iterrows():
    player_data_name = row['name1']
    season = row['season']
    cost = row['initial_cost']

    player_data.loc[(player_data['full_name'] == player_data_name) & (player_data['season'] == season), 'initial_cost'] = cost

player_data

,match_id,nick_name,full_name,pos,team,cost,season,first_appearance,initial_cost
0,918893,Cech,Petr Cech,Goalkeeper,ARS,0.0,17-18,0,5.5
1,918893,Walcott,Theo Walcott,Midfielder,ARS,0.0,17-18,0,7.5
2,918893,Ozil,Mesut Ozil,Midfielder,ARS,0.0,17-18,0,9.5
3,918893,Monreal,Nacho Monreal,Defender,ARS,0.0,17-18,0,5.5
4,918893,Ramsey,Aaron Ramsey,Midfielder,ARS,0.0,17-18,0,7.0
...,...,...,...,...,...,...,...,...,...
86803,2444849,Ait Nouri,Rayan Ait Nouri,Defender,WOL,6.0,24-25,0,4.5
86804,2444849,Rodrigo Gomes,Rodrigo Martins Gomes,Midfielder,WOL,4.5,24-25,0,5.5
86805,2444849,André,André Trindade da Costa Neto,Midfielder,WOL,5.5,24-25,0,5.0
86806,2444849,Toti,Toti António Gomes,Defender,WOL,4.5,24-25,0,4.5
86807,2444849,Agbadou,Emmanuel Agbadou,Defender,WOL,4.5,24-25,0,4.0

In [21]:
player_data.to_csv('../data/initial_player_costs.csv', index=False)

# Matching the new players to historic players

In [33]:
player_data

,match_id,nick_name,full_name,pos,team,cost,season,first_appearance,initial_cost
0,918893,Cech,Petr Cech,Goalkeeper,ARS,0.0,17-18,0,5.5
1,918893,Walcott,Theo Walcott,Midfielder,ARS,0.0,17-18,0,7.5
2,918893,Ozil,Mesut Ozil,Midfielder,ARS,0.0,17-18,0,9.5
3,918893,Monreal,Nacho Monreal,Defender,ARS,0.0,17-18,0,5.5
4,918893,Ramsey,Aaron Ramsey,Midfielder,ARS,0.0,17-18,0,7.0
...,...,...,...,...,...,...,...,...,...
86803,2444849,Ait Nouri,Rayan Ait Nouri,Defender,WOL,6.0,24-25,0,4.5
86804,2444849,Rodrigo Gomes,Rodrigo Martins Gomes,Midfielder,WOL,4.5,24-25,0,5.5
86805,2444849,André,André Trindade da Costa Neto,Midfielder,WOL,5.5,24-25,0,5.0
86806,2444849,Toti,Toti António Gomes,Defender,WOL,4.5,24-25,0,4.5
86807,2444849,Agbadou,Emmanuel Agbadou,Defender,WOL,4.5,24-25,0,4.0

In [61]:
import random as rand

def find_lookalike(player_name, team, position, season, cost):
    # Filter players by team and position
    similar_players = player_data[
        (player_data['team'] == team) &
        (player_data['pos'] == position) &
        (player_data['season'] == season) &
        (player_data['full_name'] != player_name)
    ].copy()

    # Calculate cost difference as a new column
    similar_players['cost_diff'] = (similar_players['initial_cost'] - cost).abs()

    similar_players = similar_players.drop_duplicates(subset = ["full_name"])

    smallest_cost_diff = similar_players['cost_diff'].min()

    print(similar_players[similar_players['cost_diff'] == smallest_cost_diff])

    options = similar_players[similar_players['cost_diff'] == smallest_cost_diff]

    if len(options) == 1:
        print(options.iloc[0])
    else:
        selection = rand.randint(0, len(options) - 1)
        print(options.iloc[selection])


find_lookalike("Toti António Gomes", "WOL", "Defender", "24-25", 4.5)

       match_id         nick_name             full_name       pos team  cost  \
75287   2444471            Dawson          Craig Dawson  Defender  WOL   4.2
75288   2444471           Doherty          Matt Doherty  Defender  WOL   4.5
75298   2444471         Ait Nouri       Rayan Ait Nouri  Defender  WOL   6.0
76121   2444498            Semedo         Nelson Semedo  Defender  WOL   4.5
76495   2444510  Bueno (Santiago)        Santiago Bueno  Defender  WOL   4.5
82851   2444720             Djiga  Nasser Yacouba Djiga  Defender  WOL   4.5

      season  first_appearance  initial_cost  cost_diff
75287  24-25                 0           4.5        0.0
75288  24-25                 0           4.5        0.0
75298  24-25                 0           4.5        0.0
76121  24-25                 0           4.5        0.0
76495  24-25                 0           4.5        0.0
82851  24-25                 0           4.5        0.0
match_id                 2444471
nick_name                Doherty
full_name           Matt Doherty
pos                     Defender
team                         WOL
cost                         4.5
season                     24-25
first_appearance               0
initial_cost                 4.5
cost_diff                    0.0
Name: 75288, dtype: object

In [54]:
player_data[player_data.full_name == "Aaron Ramsey"].drop_duplicates(subset = ["full_name", "team", "season"])

,match_id,nick_name,full_name,pos,team,cost,season,first_appearance,initial_cost
4,918893,Ramsey,Aaron Ramsey,Midfielder,ARS,0.0,17-18,0,7.0
10479,987593,Ramsey,Aaron Ramsey,Midfielder,ARS,0.0,18-19,0,7.5
64293,2367552,Ramsey (Aaron),Aaron Ramsey,Midfielder,BUR,4.5,23-24,0,5.0